import type { ChannelReplyMessage, ConversationNotice } from '@glimmer-cradle/extension-sdk';

export interface AudioConfig { tts: { enabled: boolean; route: { primary: string; fallbacks: string[]; circuit_breaker: { failure_threshold: number; recovery_timeout_ms: number } }; cache: { enabled: boolean; max_age_days: number }; providers: { 'dashscope-cosyvoice': { enabled: boolean; endpoint: string; model: string; format: 'wav'; sample_rate: 8000 | 16000 | 22050 | 24000 | 44100 | 48000; connect_timeout_ms: number; receive_timeout_ms: number; max_retries: number } } }; asr: { enabled: boolean; provider: 'funasr'; resource_id: string } }
export interface EmbeddingConfig { enabled: boolean; route: { provider: 'dashscope-text-embedding' | 'local-sentence-transformers' }; providers: { 'dashscope-text-embedding': { endpoint: string; model: string; dimensions: 64 | 128 | 256 | 512 | 768 | 1024 | 1536 | 2048; request_timeout_ms: number; max_retries: number }; 'local-sentence-transformers': { model_path: string; model_id: string; auto_download: boolean; device: string; batch_size: number } } }
export interface MemoryConfig { working: { max_messages_per_conversation: number; hydrate_recent_messages: number; context_message_limit: number }; conversation: { segment_target_messages: number; chapter_idle_minutes: number; chapter_segment_limit: number; state_update_messages: number; history_candidate_limit: number; history_result_limit: number; summary_max_chars: number }; experience: { enabled: boolean; pack_max_size_mb: number; flush_interval_ms: number; flush_max_buffer: number; episode_idle_seconds: number; seal_integrity_check: boolean }; consolidation: { enabled: boolean; batch_size: number; max_batch_moments: number; debounce_seconds: number; max_wait_seconds: number; lease_seconds: number; retry_base_seconds: number; minimum_salience: number; autobiographical_evidence_threshold: number; schedule_interval_seconds: number }; retrieval: { token_budget: number; candidate_limit: number; result_limit: number; semantic_weight: number } }
export type SkillProductTarget = 'any' | 'desktop' | 'personal-server';
export interface McpServerConfig { id: string; enabled: boolean; products: [SkillProductTarget, ...SkillProductTarget[]]; transport: 'stdio' | 'http' | 'websocket'; command?: string; args: string[]; url?: string; env: Record<string, string>; capability_prefix?: string; timeout_ms: number }
export interface SkillPlaneConfig { mcp_servers: McpServerConfig[]; user_skills: { enabled: boolean; root_dir: string } }
export interface ConfigurationModelAlias { alias: string; model_id: string }
export interface ConfigurationProviderDraft { key: string; api_type: string; base_url?: string; api_key?: string; clear_api_key?: boolean; temperature?: number; request_method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; request_path?: string; request_headers?: Record<string, string>; request_body_template?: string; response_extract?: string; models: [ConfigurationModelAlias, ...ConfigurationModelAlias[]] }
export interface ConfigurationProviderTestDraft extends Omit<ConfigurationProviderDraft, 'models'> {}
export interface ConfigurationProviderSnapshot { key: string; api_type: string; base_url?: string; has_api_key: boolean; temperature?: number; request_method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; request_path?: string; response_extract?: string; models: ConfigurationModelAlias[] }
export interface ConfigurationRouteSnapshot { provider_key?: string; model_alias?: string; effective_model_id?: string; ready: boolean; reason?: string }
export interface ConfigurationSnapshot { revision: string; llm: { provider_count: number; providers: ConfigurationProviderSnapshot[]; default_route: ConfigurationRouteSnapshot }; audio: AudioConfig; embedding: EmbeddingConfig; memory: MemoryConfig; skills: SkillPlaneConfig; storage: { config_root: string; data_root: string; state_root: string }; service: { cognition_ready: boolean; restart_supported: boolean } }
export interface ConfigurationSnapshotResult { request_id: string; status: 'success' | 'error'; snapshot?: ConfigurationSnapshot; message?: string }
export interface ConfigurationTestRequest { request_id: string; provider: ConfigurationProviderTestDraft }
export interface ConfigurationTestResult { request_id: string; status: 'success' | 'error'; message: string; discovered_models: string[]; latency_ms?: number }
export interface ConfigurationUpdateRequest { request_id: string; revision: string; dry_run?: boolean; llm: { default_route_provider_key?: string; default_route_model_alias?: string; providers: ConfigurationProviderDraft[]; removed_provider_keys: string[] }; audio: AudioConfig; embedding: EmbeddingConfig; memory: MemoryConfig; skills: SkillPlaneConfig }
export interface ConfigurationUpdateResult { request_id: string; status: 'preview' | 'success' | 'conflict' | 'error'; apply_state: 'unchanged' | 'restart_required' | 'restarting' | 'completed' | 'failed'; new_revision?: string; change_summary: string[]; snapshot?: ConfigurationSnapshot; message?: string }

export interface ConversationHistoryRequest { request_id: string; conversation_id?: string; scene_id?: string; thread_id?: string; actor_id?: string; source_provider_id?: string; cursor?: string; limit: number }
export interface ConversationHistoryEntry { entry_id: string; source_kind: 'conversation' | 'notice' | 'transient'; role: 'user' | 'assistant' | 'system'; status: 'committed' | 'pending' | 'thinking' | 'failed' | 'notice'; text: string; title?: string; occurred_at: string; trace_id?: string; interaction_id?: string; moment_id?: string; position?: number; conversation_id: string; scene_id: string; thread_id: string; actor_id?: string; actor_name?: string; recall_scope: string; disclosure_scope: string }
export interface ConversationHistoryResult { request_id: string; status: 'success' | 'error'; conversation?: { source_provider_id: string; scene_id: string; conversation_id: string; thread_id: string; actor_id?: string; actor_name?: string; recall_scope: string; disclosure_scope: string }; items: ConversationHistoryEntry[]; next_cursor?: string; has_more: boolean; message?: string }

export type LifecycleState = 'discovered' | 'loaded' | 'starting' | 'running' | 'stopping' | 'stopped' | 'degraded' | 'failed';
export interface ExtensionRuntimeProjection { schema: 'glimmer-cradle.extension.runtime-projection'; extension_id: string; display_name?: string; version?: string; description?: string; permissions: string[]; tags: string[]; lifecycle: LifecycleState; summary?: string; contribution_points: Array<{ id: string; title: string; description?: string; owner: 'platform' | 'extension' | 'third_party'; state: 'registered' | 'unsupported' | 'disabled'; node_kind?: string; action_kind?: string; required_permissions: string[]; metadata: Record<string, unknown> }>; capability_graph: { nodes: Array<{ id: string; contribution_point: string; kind: string; title: string; description?: string; state: string; owner: string; owner_id?: string; audience: string; required: boolean; summary: string; permissions: string[]; readiness_gates: Array<{ id: string; kind: string; state: string; summary: string; endpoint?: string; checked_at: string; latency_ms?: number; error_code?: string; error_message?: string }>; diagnostic_refs: string[]; metadata: Record<string, unknown>; updated_at: string }>; edges: Array<{ from: string; to: string; relation: string; required_state?: string; summary?: string }> }; actions: Array<{ id: string; label: string; contribution_point: string; action_kind: string; target_node_id: string; audience: string; state: string; disabled_reason?: string; permissions: string[]; confirmation_required: boolean; metadata: Record<string, unknown> }>; diagnostics: { summary: string; last_error?: string; trace_id?: string; entries: unknown[]; log_locations: string[]; recovery_actions: string[] }; updated_at: string }
export interface ExtensionInstallationProjection { extension_id: string; installed_versions: [string, ...string[]]; active_version?: string; active_profile?: string; updated_at: string }
export interface ExtensionRuntimeProjectionRequest { request_id: string; extension_id?: string }
export interface ExtensionRuntimeProjectionResult { request_id: string; status: 'success' | 'error'; projections: ExtensionRuntimeProjection[]; installations: ExtensionInstallationProjection[]; message?: string }
export type ProductExtensionInstallSource =
  | { kind: 'file'; path: string }
  | { kind: 'uploaded_package'; upload_id: string }
  | { kind: 'registry'; catalog_url: string; extension_id: string; channel?: 'stable' | 'beta' | 'nightly' }
  | { kind: 'repository'; repository: string; tag: string }
  | { kind: 'release_manifest'; url: string };
export interface ExtensionInstallPrepareRequest { request_id: string; source: ProductExtensionInstallSource }
export interface ExtensionInstallCommitRequest { request_id: string; transaction_id: string; approved_permissions: string[] }
export interface ExtensionInstallPreview { request_id: string; status: 'ready' | 'error'; transaction_id?: string; extension?: { id: string; name: string; version: string; publisher: string; description?: string; permissions: string[]; products?: string[]; platforms: string[] }; artifact?: { sha256: string; size: number; platform: string }; trust?: { source_kind: string; listing_reviewed: boolean; publisher_verified: boolean; artifact_signed: boolean; build_attested: boolean; registry_id?: string; repository?: string }; message?: string }
export interface ExtensionInstallResult { request_id: string; status: 'success' | 'cancelled' | 'error'; extension_id?: string; version?: string; already_installed?: boolean; message?: string }
export interface ExtensionUninstallRequest { request_id: string; extension_id: string; version: string }
export interface ExtensionUninstallResult { request_id: string; extension_id: string; version: string; status: 'success' | 'error'; message?: string }
export interface ExtensionLifecycleRequest { request_id: string; extension_id: string; version?: string; operation: 'start' | 'stop' }
export interface ExtensionLifecycleResult { request_id: string; extension_id: string; version?: string; operation: 'start' | 'stop'; status: 'success' | 'error'; message?: string }

export interface RuntimeProjection { runtime_id: string; owner: 'kernel' | 'cognition' | 'engine' | 'renderer' | 'extension'; phase: string; state: 'starting' | 'ready' | 'degraded' | 'failed' | 'stopped'; blocking: boolean; summary: string; details_ref?: string; duration_ms?: number; reconciler?: { desired: string; actual: string; readiness: string; resources: unknown[] } }
export interface RuntimeReadinessCatalog { updated_at: number; runtimes: RuntimeProjection[] }
export interface AudioCapabilityStatus { enabled: boolean; disabled_reason?: string; active_provider?: string; route_state: 'disabled' | 'ready' | 'degraded' | 'unavailable' | 'unknown'; providers: Array<{ provider_id: string; role: 'primary' | 'fallback'; execution: 'cloud' | 'local'; status: 'ready' | 'degraded' | 'unavailable' | 'circuit_open' | 'unknown'; message?: string }> }
export interface AudioStatusPayload { updated_at: number; tts: AudioCapabilityStatus; asr: AudioCapabilityStatus }
export interface SkillCatalogSnapshot { generatedAt: string; totalSkills: number; totalTools: number; totalResources: number; totalPrompts: number; providerCounts?: Record<string, number>; runtimeStatusCounts: Record<string, number>; providerRuntimes: Array<{ provider: { kind: string; id: string }; display_name?: string; state: string; summary: string; skill_count: number; tool_count: number; resource_count: number; prompt_count: number; error?: string; recovery_actions?: string[]; metadata?: Record<string, unknown>; updated_at?: string }>; entries: Array<{ id?: string; provider: { kind: string; id: string }; scope: { kind: string; ids?: readonly string[] }; name: string; description: string; audience: string; tools: unknown[]; resources: unknown[]; prompts: unknown[]; policy: { riskLevel: string; confirmationRequired: boolean; audit: boolean; sideEffects?: string[] }; metadata?: Record<string, unknown> }> }

export interface ProductSurfaceRequest { kind: 'heartbeat' | 'chat_input' | 'audio_input' | 'avatar_presentation' | 'avatar_intent' | 'config_snapshot_request' | 'conversation_history_request' | 'skill_catalog_request' | 'config_update_request' | 'config_test_request' | 'extension_install_prepare' | 'extension_install_commit' | 'extension_install_cancel' | 'extension_uninstall_request' | 'extension_lifecycle_request' | 'extension_command_request' | 'extension_runtime_projection_request' | 'shutdown_request' | 'core_skill_action_response' | 'core_skill_confirmation_response'; trace_id?: string; timestamp: number; chat_input?: { text: string; source_suffix?: string }; audio_input?: { audio_id: string; audio_data: string; mime_type: string; duration_ms?: number; sample_rate?: number }; avatar_presentation?: { placement_id?: string; display_scale?: number; reset_placement?: boolean }; avatar_intent?: { action_id: string; operation: 'trigger' | 'activate' | 'deactivate'; priority?: number }; config_snapshot_request?: { request_id: string }; conversation_history_request?: ConversationHistoryRequest; skill_catalog_request?: { request_id: string }; config_update_request?: ConfigurationUpdateRequest; config_test_request?: ConfigurationTestRequest; extension_install_prepare?: ExtensionInstallPrepareRequest; extension_install_commit?: ExtensionInstallCommitRequest; extension_install_cancel?: { request_id: string; transaction_id: string }; extension_uninstall_request?: ExtensionUninstallRequest; extension_lifecycle_request?: ExtensionLifecycleRequest; extension_command_request?: { request_id: string; command_id: string; args: unknown[] }; extension_runtime_projection_request?: ExtensionRuntimeProjectionRequest; shutdown_request?: { requested_by: 'control-surface'; reason?: string }; request_id?: string; status?: 'success' | 'error'; result?: unknown; message?: string; error_code?: string; operation_id?: string; recovery_actions?: string[] }
export interface ProductSurfaceProjection { kind: 'reply' | 'emotion' | 'thought' | 'audio_play' | 'audio_transcript' | 'character_presentation_projection' | 'avatar_status' | 'avatar_action_state' | 'runtime_readiness' | 'audio_status' | 'conversation_notice' | 'conversation_history_result' | 'configuration_snapshot_result' | 'configuration_update_result' | 'configuration_test_result' | 'skill_catalog_response' | 'extension_install_preview' | 'extension_install_result' | 'extension_uninstall_result' | 'extension_lifecycle_result' | 'extension_command_result' | 'extension_runtime_projection_result' | 'extension_runtime_projection_changed' | 'extension_status_changed' | 'core_skill_action_request' | 'core_skill_confirmation_request' | 'shutdown'; trace_id?: string; timestamp: number; reply?: { text: string; messages?: ChannelReplyMessage[]; emotion_snapshot?: unknown }; emotion?: unknown; thought?: { active: boolean; hint?: string }; audio_play?: unknown; audio_transcript?: unknown; character_presentation_projection?: unknown; avatar_status?: unknown; avatar_action_state?: unknown; runtime_readiness?: RuntimeReadinessCatalog; audio_status?: AudioStatusPayload; conversation_notice?: ConversationNotice; conversation_history_result?: ConversationHistoryResult; configuration_snapshot_result?: ConfigurationSnapshotResult; configuration_update_result?: ConfigurationUpdateResult; configuration_test_result?: ConfigurationTestResult; skill_catalog_response?: { request_id: string; status: 'success' | 'error'; snapshot?: SkillCatalogSnapshot; message?: string }; extension_install_preview?: ExtensionInstallPreview; extension_install_result?: ExtensionInstallResult; extension_uninstall_result?: ExtensionUninstallResult; extension_lifecycle_result?: ExtensionLifecycleResult; extension_command_result?: { request_id: string; command_id: string; status: 'success' | 'error'; result?: unknown; message?: string }; extension_runtime_projection_result?: ExtensionRuntimeProjectionResult; extension_runtime_projection_changed?: ExtensionRuntimeProjection; extension_status_changed?: { extension_id: string; event: string; message?: string }; request_id?: string; action?: string; payload?: Record<string, unknown>; confirmation?: { trace_id: string; skill_id: string; target_kind: string; target_name: string; risk_level: string; side_effects: string[] } }
