// <auto-generated>
// Generated from protocol/src/schemas/models/Presentation*Frame.schema.json.
// Run `pnpm sync:contracts`; do not edit this file directly.
// </auto-generated>
using System;

namespace GlimmerCradle.Avatar
{
    [Serializable]
    public class ReplyPayload
    {
        public string text;
        public PresentationReplyMessage[] messages = Array.Empty<PresentationReplyMessage>();
        public EmotionPayload emotion_snapshot;
    }

    [Serializable]
    public class PresentationReplyMessage
    {
        public int sequence;
        public string content_type;
        public string text;
        public string language;
    }

    [Serializable]
    public class EmotionPayload
    {
        public string emotion_type;
        public float intensity;
        public string trigger;
        public int blend_time_ms;
    }

    [Serializable]
    public class ThoughtPayload
    {
        public bool active;
        public string hint;
    }

    [Serializable]
    public class AudioPlayPayload
    {
        public string audio_id;
        public string audio_uri;
        public string audio_data;
        public string mime_type;
        public int duration_ms;
    }

    [Serializable]
    public class AudioTranscriptPayload
    {
        public string audio_id;
        public string status;
        public string text;
        public string message;
    }

    [Serializable]
    public class AvatarExpressionPayload
    {
        public string expression_id;
        public int blend_time_ms;
        public bool auto_reset;
    }

    [Serializable]
    public class AvatarMotionPayload
    {
        public string motion_id;
        public bool loop;
        public int priority;
    }

    [Serializable]
    public class AvatarLipSyncPayload
    {
        public float amplitude;
        public string source;
    }

    [Serializable]
    public class AvatarParameterPayload
    {
        public string param_id;
        public float value;
        public int fade_ms;
    }

    [Serializable]
    public class AvatarIntentPayload
    {
        public string action_id;
        public string operation;
        public string source;
        public int priority;
    }

    [Serializable]
    public class AvatarActionStatePayload
    {
        public string action_id;
        public string state;
        public string[] active_action_ids = Array.Empty<string>();
        public string message;
    }

    [Serializable]
    public class AvatarPresentationPayload
    {
        public string placement_id;
        public float display_scale;
        public bool reset_placement;
    }

    [Serializable]
    public class CharacterPresentationProjectionPayload
    {
        public string avatar_package_id;
        public string model_id;
        public string display_name;
        public string kind;
        public string backend;
        public string host_kind;
        public string avatar_state;
        public CharacterPresentationAppearancePayload appearance;
        public CharacterPresentationLifecyclePayload lifecycle;
    }

    [Serializable]
    public class AvatarStatusPayload
    {
        public string host_kind;
        public string host_id;
    }

    [Serializable]
    public class PresentationRuntimeReadinessCatalogPayload
    {
        public double updated_at;
        public PresentationRuntimeReadinessSnapshot[] runtimes = Array.Empty<PresentationRuntimeReadinessSnapshot>();
    }

    [Serializable]
    public class PresentationRuntimeResourceSnapshot
    {
        public string resource_id;
        public string resource_kind;
        public string desired_state;
        public string actual_state;
        public string readiness;
        public string summary;
        public string[] recovery_actions = Array.Empty<string>();
    }

    [Serializable]
    public class PresentationRuntimeReconcilerSnapshot
    {
        public string desired;
        public string actual;
        public string readiness;
        public PresentationRuntimeResourceSnapshot[] resources = Array.Empty<PresentationRuntimeResourceSnapshot>();
    }

    [Serializable]
    public class PresentationRuntimeReadinessSnapshot
    {
        public string runtime_id;
        public string owner;
        public string phase;
        public string state;
        public bool blocking;
        public string summary;
        public string details_ref;
        public double duration_ms;
        public PresentationRuntimeReconcilerSnapshot reconciler;
    }

    [Serializable]
    public class AudioStatusPayload
    {
        public double updated_at;
        public AudioCapabilityStatus tts;
        public AudioCapabilityStatus asr;
    }

    [Serializable]
    public class AudioCapabilityStatus
    {
        public bool enabled;
        public string disabled_reason;
        public string active_provider;
        public string route_state;
        public AudioProviderStatus[] providers = Array.Empty<AudioProviderStatus>();
    }

    [Serializable]
    public class AudioProviderStatus
    {
        public string provider_id;
        public string role;
        public string execution;
        public string status;
        public string message;
    }

    [Serializable]
    public class LoadScenePayload
    {
        public string scene_id;
        public int fade_ms;
    }

    [Serializable]
    public class UnloadScenePayload
    {
        public int fade_ms;
    }

    [Serializable]
    public class AvatarHostHelloPayload
    {
        public string host_kind;
        public string host_id;
        public string host_version;
        public string[] capabilities = Array.Empty<string>();
        public string model_id;
        public string avatar_package_id;
    }

    [Serializable]
    public class AvatarHostReadyPayload
    {
        public string host_id;
        public string model_id;
        public string avatar_package_id;
        public string worker_window_state;
        public string composition_surface_state;
        public bool first_frame_presented;
        public bool interaction_ready;
        public string summary;
    }

    [Serializable]
    public class ChatInputPayload
    {
        public string text;
        public string source_suffix;
    }

    [Serializable]
    public class AudioInputPayload
    {
        public string audio_id;
        public string audio_data;
        public string mime_type;
        public int duration_ms;
        public int sample_rate;
    }

    [Serializable]
    public class AvatarPresentationRequest
    {
        public string placement_id;
        public float display_scale;
        public bool reset_placement;
    }

    [Serializable]
    public class AvatarIntentRequest
    {
        public string action_id;
        public string operation;
        public int priority;
    }

    [Serializable]
    public class AvatarActionStateReportPayload
    {
        public string action_id;
        public string state;
        public string[] active_action_ids = Array.Empty<string>();
        public string message;
    }

    [Serializable]
    public class ShutdownRequestPayload
    {
        public string requested_by;
        public string reason;
    }

    [Serializable]
    public class PerceptionInputPayload
    {
        public string text;
        public string address_mode;
        public string scene_id;
        public string object_id;
        public object metadata;
    }

    [Serializable]
    public class SceneLifecyclePayload
    {
        public string scene_id;
        public SceneNarrativePayload narrative;
    }

    [Serializable]
    public class AnimationCompletePayload
    {
        public string animation_id;
    }

    [Serializable]
    public class AvatarHostErrorPayload
    {
        public string code;
        public string message;
        public object details;
    }

    [Serializable]
    public class SkillProviderRef
    {
        public string kind;
        public string id;
    }

    [Serializable]
    public class SkillPolicy
    {
        public string riskLevel;
        public bool confirmationRequired;
        public string[] sideEffects = Array.Empty<string>();
        public bool audit;
    }

    [Serializable]
    public class SkillToolSummary
    {
        public string name;
        public string description;
        public string audience;
        public CapabilityScope scope;
        public object parameters;
    }

    [Serializable]
    public class SkillResourceSummary
    {
        public string id;
        public string description;
        public string audience;
        public CapabilityScope scope;
        public object parameters;
    }

    [Serializable]
    public class SkillPromptSummary
    {
        public string id;
        public string description;
        public string audience;
        public CapabilityScope scope;
        public object parameters;
    }

    [Serializable]
    public class SkillCatalogEntry
    {
        public string id;
        public string name;
        public string description;
        public string audience;
        public CapabilityScope scope;
        public SkillProviderRef provider;
        public SkillToolSummary[] tools = Array.Empty<SkillToolSummary>();
        public SkillResourceSummary[] resources = Array.Empty<SkillResourceSummary>();
        public SkillPromptSummary[] prompts = Array.Empty<SkillPromptSummary>();
        public SkillPolicy policy;
        public object metadata;
    }

    [Serializable]
    public class SkillProviderRuntimeSnapshot
    {
        public SkillProviderRef provider;
        public string display_name;
        public string state;
        public string summary;
        public int skill_count;
        public int tool_count;
        public int resource_count;
        public int prompt_count;
        public string error;
        public string[] recovery_actions = Array.Empty<string>();
        public object metadata;
        public string updated_at;
    }

    [Serializable]
    public class CircuitBreakerConfig
    {
        public int failure_threshold;
        public int recovery_timeout_ms;
    }

    [Serializable]
    public class TTSRouteConfig
    {
        public string primary = "dashscope-cosyvoice";
        public string[] fallbacks = Array.Empty<string>();
        public CircuitBreakerConfig circuit_breaker;
    }

    [Serializable]
    public class TTSCacheConfig
    {
        public bool enabled;
        public int max_age_days;
    }

    [Serializable]
    public class DashScopeCosyVoiceConfig
    {
        public bool enabled;
        public string endpoint = "wss://dashscope.aliyuncs.com/api-ws/v1/inference";
        public string model = "cosyvoice-v3.5-flash";
        public string format = "wav";
        public int sample_rate;
        public int connect_timeout_ms;
        public int receive_timeout_ms;
        public int max_retries;
    }

    [Serializable]
    public class TTSProvidersConfig
    {
        public DashScopeCosyVoiceConfig dashscope-cosyvoice;
    }

    [Serializable]
    public class TTSConfig
    {
        public bool enabled;
        public TTSRouteConfig route;
        public TTSCacheConfig cache;
        public TTSProvidersConfig providers;
    }

    [Serializable]
    public class ASRConfig
    {
        public bool enabled;
        public string provider = "funasr";
        public string resource_id = "funasr.sensevoice-small";
    }

    [Serializable]
    public class EmbeddingRouteConfig
    {
        public string provider = "dashscope-text-embedding";
    }

    [Serializable]
    public class DashScopeEmbeddingProviderConfig
    {
        public string endpoint = "https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding";
        public string model = "text-embedding-v4";
        public int dimensions;
        public int request_timeout_ms;
        public int max_retries;
    }

    [Serializable]
    public class LocalEmbeddingProviderConfig
    {
        public string model_path = "embedding/m3e-small";
        public string model_id = "moka-ai/m3e-small";
        public bool auto_download;
        public string device = "cpu";
        public int batch_size;
    }

    [Serializable]
    public class EmbeddingProvidersConfig
    {
        public DashScopeEmbeddingProviderConfig dashscope-text-embedding;
        public LocalEmbeddingProviderConfig local-sentence-transformers;
    }

    [Serializable]
    public class WorkingMemoryConfig
    {
        public int max_messages_per_conversation;
        public int hydrate_recent_messages;
        public int context_message_limit;
    }

    [Serializable]
    public class ConversationProjectionConfig
    {
        public int segment_target_messages;
        public int chapter_idle_minutes;
        public int chapter_segment_limit;
        public int state_update_messages;
        public int history_candidate_limit;
        public int history_result_limit;
        public int summary_max_chars;
    }

    [Serializable]
    public class ExperienceLedgerConfig
    {
        public bool enabled;
        public int pack_max_size_mb;
        public int flush_interval_ms;
        public int flush_max_buffer;
        public int episode_idle_seconds;
        public bool seal_integrity_check;
    }

    [Serializable]
    public class ConsolidationConfig
    {
        public bool enabled;
        public int batch_size;
        public int max_batch_moments;
        public int debounce_seconds;
        public int max_wait_seconds;
        public int lease_seconds;
        public int retry_base_seconds;
        public float minimum_salience;
        public int autobiographical_evidence_threshold;
        public int schedule_interval_seconds;
    }

    [Serializable]
    public class RetrievalConfig
    {
        public int token_budget;
        public int candidate_limit;
        public int result_limit;
        public float semantic_weight;
    }

    [Serializable]
    public class McpServerConfig
    {
        public string id;
        public bool enabled;
        public string[] products = Array.Empty<string>();
        public string transport = "stdio";
        public string command;
        public string[] args = Array.Empty<string>();
        public string url;
        public McpServerConfigEnvPayload env;
        public string capability_prefix;
        public int timeout_ms;
    }

    [Serializable]
    public class UserSkillConfig
    {
        public bool enabled;
        public string root_dir = "skills";
    }

    [Serializable]
    public class ContributionPointDefinitionSnapshot
    {
        public string id;
        public string title;
        public string description;
        public string owner;
        public string state;
        public string node_kind;
        public string action_kind;
        public string[] required_permissions = Array.Empty<string>();
        public object metadata;
    }

    [Serializable]
    public class ReadinessGateSnapshot
    {
        public string id;
        public string kind;
        public string state;
        public string summary;
        public string endpoint;
        public string checked_at;
        public float latency_ms;
        public string error_code;
        public string error_message;
    }

    [Serializable]
    public class CapabilityGraphNode
    {
        public string id;
        public string contribution_point;
        public string kind;
        public string title;
        public string description;
        public string state;
        public string owner;
        public string owner_id;
        public string audience;
        public bool required;
        public string summary;
        public string[] permissions = Array.Empty<string>();
        public ReadinessGateSnapshot[] readiness_gates = Array.Empty<ReadinessGateSnapshot>();
        public string[] diagnostic_refs = Array.Empty<string>();
        public object metadata;
        public string updated_at;
    }

    [Serializable]
    public class CapabilityGraphEdge
    {
        public string from;
        public string to;
        public string relation;
        public string required_state;
        public string summary;
    }

    [Serializable]
    public class CapabilityGraphSnapshot
    {
        public CapabilityGraphNode[] nodes = Array.Empty<CapabilityGraphNode>();
        public CapabilityGraphEdge[] edges = Array.Empty<CapabilityGraphEdge>();
    }

    [Serializable]
    public class ActionIntentSnapshot
    {
        public string id;
        public string label;
        public string contribution_point;
        public string action_kind;
        public string target_node_id;
        public string audience;
        public string state;
        public string disabled_reason;
        public string[] permissions = Array.Empty<string>();
        public bool confirmation_required;
        public object metadata;
    }

    [Serializable]
    public class DiagnosticsEntry
    {
        public string id;
        public string severity;
        public string summary;
        public string node_id;
        public string trace_id;
        public string[] log_locations = Array.Empty<string>();
        public string[] recovery_actions = Array.Empty<string>();
        public object metadata;
    }

    [Serializable]
    public class DiagnosticsSnapshot
    {
        public string summary;
        public string last_error;
        public string trace_id;
        public DiagnosticsEntry[] entries = Array.Empty<DiagnosticsEntry>();
        public string[] log_locations = Array.Empty<string>();
        public string[] recovery_actions = Array.Empty<string>();
    }

    [Serializable]
    public class PresentationDownstreamFrame
    {
        public string kind;
        public string trace_id;
        public double timestamp;
        public ReplyPayload reply;
        public EmotionPayload emotion;
        public ThoughtPayload thought;
        public AudioPlayPayload audio_play;
        public AudioTranscriptPayload audio_transcript;
        public AvatarExpressionPayload expression;
        public AvatarMotionPayload motion;
        public AvatarLipSyncPayload lip_sync;
        public AvatarParameterPayload parameter;
        public AvatarIntentPayload avatar_intent;
        public AvatarActionStatePayload avatar_action_state;
        public AvatarPresentationPayload presentation;
        public CharacterPresentationProjectionPayload character_presentation_projection;
        public AvatarStatusPayload avatar_status;
        public PresentationRuntimeReadinessCatalogPayload runtime_readiness;
        public AudioStatusPayload audio_status;
        public ConversationNotice conversation_notice;
        public ConversationHistoryResult conversation_history_result;
        public SkillCatalogResponse skill_catalog_response;
        public ConfigurationSnapshotResult configuration_snapshot_result;
        public ConfigurationUpdateResult configuration_update_result;
        public ConfigurationTestResult configuration_test_result;
        public ExtensionInstallPreview extension_install_preview;
        public ExtensionInstallResult extension_install_result;
        public ExtensionUninstallResult extension_uninstall_result;
        public ExtensionLifecycleResult extension_lifecycle_result;
        public ExtensionCommandResult extension_command_result;
        public ExtensionRuntimeProjectionResult extension_runtime_projection_result;
        public ExtensionRuntimeProjection extension_runtime_projection_changed;
        public ExtensionStatusChanged extension_status_changed;
        public LoadScenePayload load_scene;
        public UnloadScenePayload unload_scene;
    }

    [Serializable]
    public class PresentationUpstreamFrame
    {
        public string kind;
        public string trace_id;
        public double timestamp;
        public AvatarHostHelloPayload host_hello;
        public AvatarHostReadyPayload host_ready;
        public ChatInputPayload chat_input;
        public AudioInputPayload audio_input;
        public AvatarPresentationRequest avatar_presentation;
        public AvatarIntentRequest avatar_intent;
        public AvatarActionStateReportPayload avatar_action_state;
        public ConfigurationSnapshotRequest config_snapshot_request;
        public ConversationHistoryRequest conversation_history_request;
        public SkillCatalogRequest skill_catalog_request;
        public ConfigurationUpdateRequest config_update_request;
        public ConfigurationTestRequest config_test_request;
        public ExtensionInstallPrepareRequest extension_install_prepare;
        public ExtensionInstallCommitRequest extension_install_commit;
        public PresentationUpstreamFrameExtensionInstallCancelPayload extension_install_cancel;
        public ExtensionUninstallRequest extension_uninstall_request;
        public ExtensionLifecycleRequest extension_lifecycle_request;
        public ExtensionCommandRequest extension_command_request;
        public ExtensionRuntimeProjectionRequest extension_runtime_projection_request;
        public ShutdownRequestPayload shutdown_request;
        public PerceptionInputPayload perception;
        public SceneLifecyclePayload scene_loaded;
        public SceneLifecyclePayload scene_unloaded;
        public AnimationCompletePayload animation_complete;
        public AvatarHostErrorPayload error;
    }

    [Serializable]
    public class ConversationNotice
    {
        public string code;
        public string level;
        public string title;
        public string message;
        public string action_route;
        public string action_label;
    }

    [Serializable]
    public class ConversationHistoryResult
    {
        public string request_id;
        public string status;
        public ConversationHistoryResultConversationPayload conversation;
        public ConversationHistoryEntry[] items = Array.Empty<ConversationHistoryEntry>();
        public string next_cursor;
        public bool has_more;
        public string message;
    }

    [Serializable]
    public class ConversationHistoryEntry
    {
        public string entry_id;
        public string source_kind;
        public string role;
        public string status;
        public string text;
        public string title;
        public string occurred_at;
        public string trace_id;
        public string interaction_id;
        public string moment_id;
        public int position;
        public string conversation_id;
        public string scene_id;
        public string thread_id;
        public string actor_id;
        public string actor_name;
        public string recall_scope;
        public string disclosure_scope;
    }

    [Serializable]
    public class SkillCatalogResponse
    {
        public string request_id;
        public string status;
        public SkillCatalogSnapshot snapshot;
        public string message;
    }

    [Serializable]
    public class SkillCatalogSnapshot
    {
        public string generatedAt;
        public int totalSkills;
        public SkillCatalogSnapshotProviderCountsPayload providerCounts;
        public SkillCatalogSnapshotRuntimeStatusCountsPayload runtimeStatusCounts;
        public int totalTools;
        public int totalResources;
        public int totalPrompts;
        public SkillProviderRuntimeSnapshot[] providerRuntimes = Array.Empty<SkillProviderRuntimeSnapshot>();
        public SkillCatalogEntry[] entries = Array.Empty<SkillCatalogEntry>();
    }

    [Serializable]
    public class ConfigurationSnapshotResult
    {
        public string request_id;
        public string status;
        public ConfigurationSnapshot snapshot;
        public string message;
    }

    [Serializable]
    public class ConfigurationSnapshot
    {
        public string revision;
        public ConfigurationSnapshotLlmPayload llm;
        public AudioConfig audio;
        public EmbeddingConfig embedding;
        public MemoryConfig memory;
        public SkillPlaneConfig skills;
        public ConfigurationSnapshotStoragePayload storage;
        public ConfigurationSnapshotServicePayload service;
    }

    [Serializable]
    public class ConfigurationProviderSnapshot
    {
        public string key;
        public string api_type;
        public string base_url;
        public bool has_api_key;
        public float temperature;
        public string request_method;
        public string request_path;
        public string response_extract;
        public ConfigurationModelAlias[] models = Array.Empty<ConfigurationModelAlias>();
    }

    [Serializable]
    public class ConfigurationModelAlias
    {
        public string alias;
        public string model_id;
    }

    [Serializable]
    public class ConfigurationRouteSnapshot
    {
        public string provider_key;
        public string model_alias;
        public string effective_model_id;
        public bool ready;
        public string reason;
    }

    [Serializable]
    public class AudioConfig
    {
        public TTSConfig tts;
        public ASRConfig asr;
    }

    [Serializable]
    public class EmbeddingConfig
    {
        public bool enabled;
        public EmbeddingRouteConfig route;
        public EmbeddingProvidersConfig providers;
    }

    [Serializable]
    public class MemoryConfig
    {
        public WorkingMemoryConfig working;
        public ConversationProjectionConfig conversation;
        public ExperienceLedgerConfig experience;
        public ConsolidationConfig consolidation;
        public RetrievalConfig retrieval;
    }

    [Serializable]
    public class SkillPlaneConfig
    {
        public McpServerConfig[] mcp_servers = Array.Empty<McpServerConfig>();
        public UserSkillConfig user_skills;
    }

    [Serializable]
    public class ConfigurationUpdateResult
    {
        public string request_id;
        public string status;
        public string apply_state;
        public string new_revision;
        public string[] change_summary = Array.Empty<string>();
        public ConfigurationSnapshot snapshot;
        public string message;
    }

    [Serializable]
    public class ConfigurationTestResult
    {
        public string request_id;
        public string status;
        public string message;
        public string[] discovered_models = Array.Empty<string>();
        public float latency_ms;
    }

    [Serializable]
    public class ExtensionInstallPreview
    {
        public string request_id;
        public string status;
        public string message;
        public string transaction_id;
        public ExtensionInstallPreviewActivationProfilePayload activation_profile;
        public ExtensionInstallPreviewAvailableProfilesPayload[] available_profiles = Array.Empty<ExtensionInstallPreviewAvailableProfilesPayload>();
        public string[] effective_permissions = Array.Empty<string>();
        public string[] effective_resources = Array.Empty<string>();
        public string[] effective_capabilities = Array.Empty<string>();
        public string[] effective_settings = Array.Empty<string>();
        public ExtensionInstallPreviewExtensionPayload extension;
        public ExtensionInstallPreviewArtifactPayload artifact;
        public ExtensionInstallPreviewTrustPayload trust;
    }

    [Serializable]
    public class ExtensionInstallResult
    {
        public string request_id;
        public string status;
        public string message;
        public string extension_id;
        public string version;
        public bool already_installed;
    }

    [Serializable]
    public class ExtensionUninstallResult
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string status;
        public string message;
    }

    [Serializable]
    public class ExtensionLifecycleResult
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string activation_profile;
        public string operation;
        public string status;
        public string message;
    }

    [Serializable]
    public class ExtensionCommandResult
    {
        public string request_id;
        public string command_id;
        public string status;
        public object result;
        public string message;
    }

    [Serializable]
    public class ExtensionRuntimeProjectionResult
    {
        public string request_id;
        public string status;
        public ExtensionRuntimeProjection[] projections = Array.Empty<ExtensionRuntimeProjection>();
        public ExtensionInstallationProjection[] installations = Array.Empty<ExtensionInstallationProjection>();
        public string message;
    }

    [Serializable]
    public class ExtensionRuntimeProjection
    {
        public string schema;
        public string extension_id;
        public string display_name;
        public string version;
        public string description;
        public string[] permissions = Array.Empty<string>();
        public string[] tags = Array.Empty<string>();
        public string lifecycle;
        public string summary;
        public ContributionPointDefinitionSnapshot[] contribution_points = Array.Empty<ContributionPointDefinitionSnapshot>();
        public CapabilityGraphSnapshot capability_graph;
        public ActionIntentSnapshot[] actions = Array.Empty<ActionIntentSnapshot>();
        public DiagnosticsSnapshot diagnostics;
        public string updated_at;
    }

    [Serializable]
    public class ExtensionInstallationProjection
    {
        public string extension_id;
        public string[] installed_versions = Array.Empty<string>();
        public string active_version;
        public string active_profile;
        public string updated_at;
    }

    [Serializable]
    public class ExtensionStatusChanged
    {
        public string extension_id;
        public string event;
        public string message;
    }

    [Serializable]
    public class ConfigurationSnapshotRequest
    {
        public string request_id;
    }

    [Serializable]
    public class ConversationHistoryRequest
    {
        public string request_id;
        public string conversation_id;
        public string scene_id;
        public string thread_id;
        public string actor_id;
        public string source_provider_id;
        public string cursor;
        public int limit;
    }

    [Serializable]
    public class SkillCatalogRequest
    {
        public string request_id;
    }

    [Serializable]
    public class ConfigurationUpdateRequest
    {
        public string request_id;
        public string revision;
        public bool dry_run;
        public ConfigurationUpdateRequestLlmPayload llm;
        public AudioConfig audio;
        public EmbeddingConfig embedding;
        public MemoryConfig memory;
        public SkillPlaneConfig skills;
    }

    [Serializable]
    public class ConfigurationProviderDraft
    {
        public string key;
        public string api_type;
        public string base_url;
        public string api_key;
        public bool clear_api_key;
        public float temperature;
        public string request_method;
        public string request_path;
        public ConfigurationProviderDraftRequestHeadersPayload request_headers;
        public string request_body_template;
        public string response_extract;
        public ConfigurationModelAlias[] models = Array.Empty<ConfigurationModelAlias>();
    }

    [Serializable]
    public class ConfigurationTestRequest
    {
        public string request_id;
        public ConfigurationProviderTestDraft provider;
    }

    [Serializable]
    public class ConfigurationProviderTestDraft
    {
        public string key;
        public string api_type;
        public string base_url;
        public string api_key;
        public bool clear_api_key;
        public float temperature;
        public string request_method;
        public string request_path;
        public ConfigurationProviderTestDraftRequestHeadersPayload request_headers;
        public string request_body_template;
        public string response_extract;
    }

    [Serializable]
    public class ExtensionInstallPrepareRequest
    {
        public string request_id;
        public string activation_profile;
        public object source;
    }

    [Serializable]
    public class ExtensionInstallCommitRequest
    {
        public string request_id;
        public string transaction_id;
        public string[] approved_permissions = Array.Empty<string>();
    }

    [Serializable]
    public class ExtensionUninstallRequest
    {
        public string request_id;
        public string extension_id;
        public string version;
    }

    [Serializable]
    public class ExtensionLifecycleRequest
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string activation_profile;
        public string operation;
    }

    [Serializable]
    public class ExtensionCommandRequest
    {
        public string request_id;
        public string command_id;
        public object[] args = Array.Empty<object>();
    }

    [Serializable]
    public class ExtensionRuntimeProjectionRequest
    {
        public string request_id;
        public string extension_id;
    }

    [Serializable]
    public class CharacterPresentationAppearancePayload
    {
        public string placement_id;
        public float display_scale;
    }

    [Serializable]
    public class CharacterPresentationLifecyclePayload
    {
        public string worker_window_state;
        public string composition_surface_state;
        public bool first_frame_presented;
        public bool interaction_ready;
        public bool ready;
        public string summary;
    }

    [Serializable]
    public class SceneNarrativePayload
    {
        public string scene_summary;
        public string atmosphere;
    }

    [Serializable]
    public class McpServerConfigEnvPayload
    {
    }

    [Serializable]
    public class PresentationUpstreamFrameExtensionInstallCancelPayload
    {
        public string request_id;
        public string transaction_id;
    }

    [Serializable]
    public class ConversationHistoryResultConversationPayload
    {
        public string source_provider_id;
        public string scene_id;
        public string conversation_id;
        public string thread_id;
        public string actor_id;
        public string actor_name;
        public string recall_scope;
        public string disclosure_scope;
    }

    [Serializable]
    public class SkillCatalogSnapshotProviderCountsPayload
    {
        public int core;
        public int extension;
        public int mcp_server;
        public int user;
    }

    [Serializable]
    public class SkillCatalogSnapshotRuntimeStatusCountsPayload
    {
        public int ready;
        public int contract_only;
    }

    [Serializable]
    public class ConfigurationSnapshotLlmPayload
    {
        public int provider_count;
        public ConfigurationProviderSnapshot[] providers = Array.Empty<ConfigurationProviderSnapshot>();
        public ConfigurationRouteSnapshot default_route;
    }

    [Serializable]
    public class ConfigurationSnapshotStoragePayload
    {
        public string config_root;
        public string data_root;
        public string state_root;
    }

    [Serializable]
    public class ConfigurationSnapshotServicePayload
    {
        public bool cognition_ready;
        public bool restart_supported;
    }

    [Serializable]
    public class ExtensionInstallPreviewActivationProfilePayload
    {
        public string id;
        public string title;
        public string description;
        public bool default;
    }

    [Serializable]
    public class ExtensionInstallPreviewExtensionPayload
    {
        public string id;
        public string name;
        public string version;
        public string publisher;
        public string description;
        public string[] permissions = Array.Empty<string>();
        public string[] platforms = Array.Empty<string>();
    }

    [Serializable]
    public class ExtensionInstallPreviewArtifactPayload
    {
        public string sha256;
        public int size;
        public string platform;
    }

    [Serializable]
    public class ExtensionInstallPreviewTrustPayload
    {
        public string source_kind;
        public bool listing_reviewed;
        public bool publisher_verified;
        public bool artifact_signed;
        public bool build_attested;
        public string registry_id;
        public string repository;
    }

    [Serializable]
    public class ConfigurationUpdateRequestLlmPayload
    {
        public string default_route_provider_key;
        public string default_route_model_alias;
        public ConfigurationProviderDraft[] providers = Array.Empty<ConfigurationProviderDraft>();
        public string[] removed_provider_keys = Array.Empty<string>();
    }

    [Serializable]
    public class ConfigurationProviderDraftRequestHeadersPayload
    {
    }

    [Serializable]
    public class ConfigurationProviderTestDraftRequestHeadersPayload
    {
    }

}
