// <auto-generated>
// Generated from protocol/src/schemas/models/Presentation*Frame.schema.json.
// Run `pnpm sync:contracts`; do not edit this file directly.
// </auto-generated>
using System;

namespace GlimmerCradle.Avatar
{
    [Serializable]
    public class ReplyPayload
    {
        public string text;
        public PresentationReplyMessage[] messages = Array.Empty<PresentationReplyMessage>();
        public EmotionPayload emotion_snapshot;
    }

    [Serializable]
    public class PresentationReplyMessage
    {
        public int sequence;
        public string content_type;
        public string text;
        public string language;
    }

    [Serializable]
    public class EmotionPayload
    {
        public string emotion_type;
        public float intensity;
        public string trigger;
        public int blend_time_ms;
    }

    [Serializable]
    public class ThoughtPayload
    {
        public bool active;
        public string hint;
    }

    [Serializable]
    public class AudioPlayPayload
    {
        public string audio_id;
        public string audio_uri;
        public string audio_data;
        public string mime_type;
        public int duration_ms;
    }

    [Serializable]
    public class AudioTranscriptPayload
    {
        public string audio_id;
        public string status;
        public string text;
        public string message;
    }

    [Serializable]
    public class AvatarExpressionPayload
    {
        public string expression_id;
        public int blend_time_ms;
        public bool auto_reset;
    }

    [Serializable]
    public class AvatarMotionPayload
    {
        public string motion_id;
        public bool loop;
        public int priority;
    }

    [Serializable]
    public class AvatarLipSyncPayload
    {
        public float amplitude;
        public string source;
    }

    [Serializable]
    public class AvatarParameterPayload
    {
        public string param_id;
        public float value;
        public int fade_ms;
    }

    [Serializable]
    public class AvatarIntentPayload
    {
        public string action_id;
        public string operation;
        public string source;
        public int priority;
    }

    [Serializable]
    public class AvatarActionStatePayload
    {
        public string action_id;
        public string state;
        public string[] active_action_ids = Array.Empty<string>();
        public string message;
    }

    [Serializable]
    public class AvatarPresentationPayload
    {
        public string placement_id;
        public float display_scale;
        public bool reset_placement;
    }

    [Serializable]
    public class CharacterPresentationProjectionPayload
    {
        public string avatar_package_id;
        public string model_id;
        public string display_name;
        public string kind;
        public string backend;
        public string host_kind;
        public string avatar_state;
        public CharacterPresentationAppearancePayload appearance;
        public CharacterPresentationLifecyclePayload lifecycle;
    }

    [Serializable]
    public class AvatarStatusPayload
    {
        public string host_kind;
        public string host_id;
    }

    [Serializable]
    public class PresentationRuntimeReadinessCatalogPayload
    {
        public double updated_at;
        public PresentationRuntimeReadinessSnapshot[] runtimes = Array.Empty<PresentationRuntimeReadinessSnapshot>();
    }

    [Serializable]
    public class PresentationRuntimeResourceSnapshot
    {
        public string resource_id;
        public string resource_kind;
        public string desired_state;
        public string actual_state;
        public string readiness;
        public string summary;
        public string[] recovery_actions = Array.Empty<string>();
    }

    [Serializable]
    public class PresentationRuntimeReconcilerSnapshot
    {
        public string desired;
        public string actual;
        public string readiness;
        public PresentationRuntimeResourceSnapshot[] resources = Array.Empty<PresentationRuntimeResourceSnapshot>();
    }

    [Serializable]
    public class PresentationRuntimeReadinessSnapshot
    {
        public string runtime_id;
        public string owner;
        public string phase;
        public string state;
        public bool blocking;
        public string summary;
        public string details_ref;
        public double duration_ms;
        public PresentationRuntimeReconcilerSnapshot reconciler;
    }

    [Serializable]
    public class AudioStatusPayload
    {
        public double updated_at;
        public AudioCapabilityStatus tts;
        public AudioCapabilityStatus asr;
    }

    [Serializable]
    public class AudioCapabilityStatus
    {
        public bool enabled;
        public string disabled_reason;
        public string active_provider;
        public string route_state;
        public AudioProviderStatus[] providers = Array.Empty<AudioProviderStatus>();
    }

    [Serializable]
    public class AudioProviderStatus
    {
        public string provider_id;
        public string role;
        public string execution;
        public string status;
        public string message;
    }

    [Serializable]
    public class LoadScenePayload
    {
        public string scene_id;
        public int fade_ms;
    }

    [Serializable]
    public class UnloadScenePayload
    {
        public int fade_ms;
    }

    [Serializable]
    public class AvatarHostHelloPayload
    {
        public string host_kind;
        public string host_id;
        public string host_version;
        public string[] capabilities = Array.Empty<string>();
        public string model_id;
        public string avatar_package_id;
    }

    [Serializable]
    public class AvatarHostReadyPayload
    {
        public string host_id;
        public string model_id;
        public string avatar_package_id;
        public string worker_window_state;
        public string composition_surface_state;
        public bool first_frame_presented;
        public bool interaction_ready;
        public string summary;
    }

    [Serializable]
    public class ChatInputPayload
    {
        public string text;
        public string source_suffix;
    }

    [Serializable]
    public class AudioInputPayload
    {
        public string audio_id;
        public string audio_data;
        public string mime_type;
        public int duration_ms;
        public int sample_rate;
    }

    [Serializable]
    public class AvatarPresentationRequest
    {
        public string placement_id;
        public float display_scale;
        public bool reset_placement;
    }

    [Serializable]
    public class AvatarIntentRequest
    {
        public string action_id;
        public string operation;
        public int priority;
    }

    [Serializable]
    public class AvatarActionStateReportPayload
    {
        public string action_id;
        public string state;
        public string[] active_action_ids = Array.Empty<string>();
        public string message;
    }

    [Serializable]
    public class ShutdownRequestPayload
    {
        public string requested_by;
        public string reason;
    }

    [Serializable]
    public class PerceptionInputPayload
    {
        public string text;
        public string address_mode;
        public string scene_id;
        public string object_id;
        public object metadata;
    }

    [Serializable]
    public class SceneLifecyclePayload
    {
        public string scene_id;
        public SceneNarrativePayload narrative;
    }

    [Serializable]
    public class AnimationCompletePayload
    {
        public string animation_id;
    }

    [Serializable]
    public class AvatarHostErrorPayload
    {
        public string code;
        public string message;
        public object details;
    }

    [Serializable]
    public class ContributionPointDefinitionSnapshot
    {
        public string id;
        public string title;
        public string description;
        public string owner;
        public string state;
        public string node_kind;
        public string action_kind;
        public string[] required_permissions = Array.Empty<string>();
        public object metadata;
    }

    [Serializable]
    public class ReadinessGateSnapshot
    {
        public string id;
        public string kind;
        public string state;
        public string summary;
        public string endpoint;
        public string checked_at;
        public float latency_ms;
        public string error_code;
        public string error_message;
    }

    [Serializable]
    public class CapabilityGraphNode
    {
        public string id;
        public string contribution_point;
        public string kind;
        public string title;
        public string description;
        public string state;
        public string owner;
        public string owner_id;
        public string audience;
        public bool required;
        public string summary;
        public string[] permissions = Array.Empty<string>();
        public ReadinessGateSnapshot[] readiness_gates = Array.Empty<ReadinessGateSnapshot>();
        public string[] diagnostic_refs = Array.Empty<string>();
        public object metadata;
        public string updated_at;
    }

    [Serializable]
    public class CapabilityGraphEdge
    {
        public string from;
        public string to;
        public string relation;
        public string required_state;
        public string summary;
    }

    [Serializable]
    public class CapabilityGraphSnapshot
    {
        public CapabilityGraphNode[] nodes = Array.Empty<CapabilityGraphNode>();
        public CapabilityGraphEdge[] edges = Array.Empty<CapabilityGraphEdge>();
    }

    [Serializable]
    public class ActionIntentSnapshot
    {
        public string id;
        public string label;
        public string contribution_point;
        public string action_kind;
        public string target_node_id;
        public string audience;
        public string state;
        public string disabled_reason;
        public string[] permissions = Array.Empty<string>();
        public bool confirmation_required;
        public object metadata;
    }

    [Serializable]
    public class DiagnosticsEntry
    {
        public string id;
        public string severity;
        public string summary;
        public string node_id;
        public string trace_id;
        public string[] log_locations = Array.Empty<string>();
        public string[] recovery_actions = Array.Empty<string>();
        public object metadata;
    }

    [Serializable]
    public class DiagnosticsSnapshot
    {
        public string summary;
        public string last_error;
        public string trace_id;
        public DiagnosticsEntry[] entries = Array.Empty<DiagnosticsEntry>();
        public string[] log_locations = Array.Empty<string>();
        public string[] recovery_actions = Array.Empty<string>();
    }

    [Serializable]
    public class PresentationDownstreamFrame
    {
        public string kind;
        public string trace_id;
        public double timestamp;
        public ReplyPayload reply;
        public EmotionPayload emotion;
        public ThoughtPayload thought;
        public AudioPlayPayload audio_play;
        public AudioTranscriptPayload audio_transcript;
        public AvatarExpressionPayload expression;
        public AvatarMotionPayload motion;
        public AvatarLipSyncPayload lip_sync;
        public AvatarParameterPayload parameter;
        public AvatarIntentPayload avatar_intent;
        public AvatarActionStatePayload avatar_action_state;
        public AvatarPresentationPayload presentation;
        public CharacterPresentationProjectionPayload character_presentation_projection;
        public AvatarStatusPayload avatar_status;
        public PresentationRuntimeReadinessCatalogPayload runtime_readiness;
        public AudioStatusPayload audio_status;
        public ExtensionInstallPreview extension_install_preview;
        public ExtensionInstallResult extension_install_result;
        public ExtensionUninstallResult extension_uninstall_result;
        public ExtensionLifecycleResult extension_lifecycle_result;
        public ExtensionCommandResult extension_command_result;
        public ExtensionRuntimeProjectionResult extension_runtime_projection_result;
        public ExtensionRuntimeProjection extension_runtime_projection_changed;
        public ExtensionStatusChanged extension_status_changed;
        public LoadScenePayload load_scene;
        public UnloadScenePayload unload_scene;
    }

    [Serializable]
    public class PresentationUpstreamFrame
    {
        public string kind;
        public string trace_id;
        public double timestamp;
        public AvatarHostHelloPayload host_hello;
        public AvatarHostReadyPayload host_ready;
        public ChatInputPayload chat_input;
        public AudioInputPayload audio_input;
        public AvatarPresentationRequest avatar_presentation;
        public AvatarIntentRequest avatar_intent;
        public AvatarActionStateReportPayload avatar_action_state;
        public ExtensionInstallPrepareRequest extension_install_prepare;
        public ExtensionInstallCommitRequest extension_install_commit;
        public PresentationUpstreamFrameExtensionInstallCancelPayload extension_install_cancel;
        public ExtensionUninstallRequest extension_uninstall_request;
        public ExtensionLifecycleRequest extension_lifecycle_request;
        public ExtensionCommandRequest extension_command_request;
        public ExtensionRuntimeProjectionRequest extension_runtime_projection_request;
        public ShutdownRequestPayload shutdown_request;
        public PerceptionInputPayload perception;
        public SceneLifecyclePayload scene_loaded;
        public SceneLifecyclePayload scene_unloaded;
        public AnimationCompletePayload animation_complete;
        public AvatarHostErrorPayload error;
    }

    [Serializable]
    public class ExtensionInstallPreview
    {
        public string request_id;
        public string status;
        public string message;
        public string transaction_id;
        public ExtensionInstallPreviewExtensionPayload extension;
        public ExtensionInstallPreviewArtifactPayload artifact;
        public ExtensionInstallPreviewTrustPayload trust;
    }

    [Serializable]
    public class ExtensionInstallResult
    {
        public string request_id;
        public string status;
        public string message;
        public string extension_id;
        public string version;
        public bool already_installed;
    }

    [Serializable]
    public class ExtensionUninstallResult
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string status;
        public string message;
    }

    [Serializable]
    public class ExtensionLifecycleResult
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string operation;
        public string status;
        public string message;
    }

    [Serializable]
    public class ExtensionCommandResult
    {
        public string request_id;
        public string command_id;
        public string status;
        public object result;
        public string message;
    }

    [Serializable]
    public class ExtensionRuntimeProjectionResult
    {
        public string request_id;
        public string status;
        public ExtensionRuntimeProjection[] projections = Array.Empty<ExtensionRuntimeProjection>();
        public ExtensionInstallationProjection[] installations = Array.Empty<ExtensionInstallationProjection>();
        public string message;
    }

    [Serializable]
    public class ExtensionRuntimeProjection
    {
        public string schema;
        public string extension_id;
        public string display_name;
        public string version;
        public string description;
        public string[] permissions = Array.Empty<string>();
        public string[] tags = Array.Empty<string>();
        public string lifecycle;
        public string summary;
        public ContributionPointDefinitionSnapshot[] contribution_points = Array.Empty<ContributionPointDefinitionSnapshot>();
        public CapabilityGraphSnapshot capability_graph;
        public ActionIntentSnapshot[] actions = Array.Empty<ActionIntentSnapshot>();
        public DiagnosticsSnapshot diagnostics;
        public string updated_at;
    }

    [Serializable]
    public class ExtensionInstallationProjection
    {
        public string extension_id;
        public string[] installed_versions = Array.Empty<string>();
        public string active_version;
        public string updated_at;
    }

    [Serializable]
    public class ExtensionStatusChanged
    {
        public string extension_id;
        public string event;
        public string message;
    }

    [Serializable]
    public class ExtensionInstallPrepareRequest
    {
        public string request_id;
        public object source;
    }

    [Serializable]
    public class ExtensionInstallCommitRequest
    {
        public string request_id;
        public string transaction_id;
        public string[] approved_permissions = Array.Empty<string>();
    }

    [Serializable]
    public class ExtensionUninstallRequest
    {
        public string request_id;
        public string extension_id;
        public string version;
    }

    [Serializable]
    public class ExtensionLifecycleRequest
    {
        public string request_id;
        public string extension_id;
        public string version;
        public string operation;
    }

    [Serializable]
    public class ExtensionCommandRequest
    {
        public string request_id;
        public string command_id;
        public object[] args = Array.Empty<object>();
    }

    [Serializable]
    public class ExtensionRuntimeProjectionRequest
    {
        public string request_id;
        public string extension_id;
    }

    [Serializable]
    public class CharacterPresentationAppearancePayload
    {
        public string placement_id;
        public float display_scale;
    }

    [Serializable]
    public class CharacterPresentationLifecyclePayload
    {
        public string worker_window_state;
        public string composition_surface_state;
        public bool first_frame_presented;
        public bool interaction_ready;
        public bool ready;
        public string summary;
    }

    [Serializable]
    public class SceneNarrativePayload
    {
        public string scene_summary;
        public string atmosphere;
    }

    [Serializable]
    public class PresentationUpstreamFrameExtensionInstallCancelPayload
    {
        public string request_id;
        public string transaction_id;
    }

    [Serializable]
    public class ExtensionInstallPreviewExtensionPayload
    {
        public string id;
        public string name;
        public string version;
        public string publisher;
        public string description;
        public string[] permissions = Array.Empty<string>();
        public string[] platforms = Array.Empty<string>();
    }

    [Serializable]
    public class ExtensionInstallPreviewArtifactPayload
    {
        public string sha256;
        public int size;
        public string platform;
    }

    [Serializable]
    public class ExtensionInstallPreviewTrustPayload
    {
        public string source_kind;
        public bool listing_reviewed;
        public bool publisher_verified;
        public bool artifact_signed;
        public bool build_attested;
        public string registry_id;
        public string repository;
    }

}
