import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { EventEmitter } from 'node:events';

export interface ProcessTreeStartRequest { readonly program: string; readonly args: readonly string[]; readonly cwd: string; readonly env: NodeJS.ProcessEnv; readonly session: string; }
export interface ProcessTreeAuthority { start(request: ProcessTreeStartRequest): Promise<ProcessTreeChild>; stop(): Promise<{ terminated: boolean; active_process_count: number }>; }
export interface ProcessTreeChild { readonly pid?: number; readonly exitCode: number | null; readonly signalCode: NodeJS.Signals | null; once(event: 'error', listener: (error: Error) => void): this; once(event: 'exit', listener: (code: number | null, signal: NodeJS.Signals | null) => void): this; kill(signal?: NodeJS.Signals): boolean; }
interface FrameResponse { readonly code: number; readonly session: string; readonly rootPid: number; readonly active: number; }

export class NativeProcessTreeAuthority implements ProcessTreeAuthority {
  private helper: ChildProcessWithoutNullStreams | null = null;
  private pending: Array<{ readonly op: number; readonly resolve: (value: FrameResponse) => void; readonly reject: (reason: Error) => void }> = [];
  private buffer = Buffer.alloc(0);
  private session = '';
  public constructor(private readonly helperPath: string, private readonly spawnHelper = spawn) {}
  public async start(request: ProcessTreeStartRequest): Promise<ProcessTreeChild> { this.session = request.session; await this.ensure(request.cwd, request.env); const response = await this.request(1, request.session, request.program, request.cwd, request.args); if (response.code !== 0 || response.rootPid <= 0) throw new Error('desktop_process_tree_start_failed'); return new BridgeChild(response.rootPid, this); }
  public async stop(): Promise<{ terminated: boolean; active_process_count: number }> { const helper = this.helper; if (!helper) throw new Error('desktop_process_tree_helper_unavailable'); const response = await this.request(2, this.session, '', '', []); if (response.code !== 0 || response.active !== 0) return { terminated: false, active_process_count: response.active }; helper.stdin.end(); this.helper = null; return { terminated: true, active_process_count: 0 }; }
  private async ensure(cwd: string, env: NodeJS.ProcessEnv): Promise<void> { if (this.helper) return; const helper = this.spawnHelper(this.helperPath, [], { cwd, env, windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] }); this.helper = helper; helper.stdout.on('data', (chunk) => this.consume(Buffer.from(chunk))); helper.once('exit', () => { this.helper = null; for (const item of this.pending.splice(0)) item.reject(new Error('desktop_process_tree_helper_exit')); }); }
  private request(op: number, session: string, program: string, cwd: string, args: readonly string[]): Promise<FrameResponse> { const helper = this.helper; if (!helper) return Promise.reject(new Error('desktop_process_tree_helper_unavailable')); return new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('desktop_process_tree_protocol_timeout')), 10_000); this.pending.push({ op, resolve: (value) => { clearTimeout(timer); resolve(value); }, reject: (error) => { clearTimeout(timer); reject(error); } }); helper.stdin.write(encodeRequest(op, session, program, cwd, args)); }); }
  private consume(chunk: Buffer): void { this.buffer = Buffer.concat([this.buffer, chunk]); while (this.buffer.length >= 4) { const size = this.buffer.readUInt32LE(0); if (size > 1024 * 1024 || this.buffer.length < size + 4) return; const frame = decodeResponse(this.buffer.subarray(4, size + 4)); this.buffer = this.buffer.subarray(size + 4); const pending = this.pending.shift(); if (pending) pending.resolve(frame); } }
}
class BridgeChild extends EventEmitter implements ProcessTreeChild { public exitCode: number | null = null; public signalCode: NodeJS.Signals | null = null; public constructor(public readonly pid: number, private readonly authority: ProcessTreeAuthority) { super(); } public kill(signal: NodeJS.Signals = 'SIGTERM'): boolean { void this.authority.stop().then(() => { this.signalCode = signal; this.emit('exit', null, signal); }); return true; } }
export function encodeRequest(op: number, session: string, program: string, cwd: string, args: readonly string[]): Buffer { const fields = [Buffer.from(session), Buffer.from(program), Buffer.from(cwd), ...args.map((arg) => Buffer.from(arg))]; const size = 8 + fields.reduce((total, field) => total + 4 + field.length, 0); const body = Buffer.alloc(size); let offset = 0; body.writeUInt32LE(op, offset); offset += 4; for (const field of fields.slice(0, 3)) { body.writeUInt32LE(field.length, offset); offset += 4; field.copy(body, offset); offset += field.length; } body.writeUInt32LE(args.length, offset); offset += 4; for (const field of fields.slice(3)) { body.writeUInt32LE(field.length, offset); offset += 4; field.copy(body, offset); offset += field.length; } const frame = Buffer.alloc(body.length + 4); frame.writeUInt32LE(body.length, 0); body.copy(frame, 4); return frame; }
function decodeResponse(body: Buffer): FrameResponse { let offset = 0; const code = body.readUInt32LE(offset); offset += 4; const sessionSize = body.readUInt32LE(offset); offset += 4; const session = body.subarray(offset, offset + sessionSize).toString('utf8'); offset += sessionSize; return { code, session, rootPid: body.readUInt32LE(offset), active: body.readUInt32LE(offset + 4) }; }
