export {
  BuiltInContributionPoint,
  BuiltInContributionPointDefinitions,
  EXTENSION_ID_PATTERN,
  EXTENSION_VERSION_PATTERN,
  getEffectiveContributionIds,
  getExtensionContributions,
  getManagedResourceContributions,
  listExtensionActivationProfiles,
  materializeManifestForActivationProfile,
  resolveExtensionActivationProfile,
} from './contracts';
export type {
  BuiltInContributionPointId,
  ExtensionActivationProfileAvailability,
  ExtensionActivationProfileContext,
  ExtensionActivationProfileResolution,
  ExtensionManifestInput,
} from './contracts';
export type {
  ActivationProfileId,
  ActivationProfileRequirements,
  CapabilityAudience,
  CapabilityScope,
  ContributionDeclaration,
  ContributionDependency,
  ContributionPointDefinition,
  ContributionPointId,
  ContributionRequirements,
  ExtensionActivationProfile,
  ExtensionCapabilityContribution,
  ExtensionCommandContribution,
  ExtensionCommandPrecondition,
  ExtensionContributions,
  ExtensionEngineConstraint,
  ExtensionManifest,
  ExtensionManagementSurfaceContribution,
  ExtensionPlatform,
  ExtensionProductTarget,
  ExtensionSettingContribution,
  ExtensionSkillContribution,
  ExtensionSkillPolicyContribution,
  ExtensionSkillPromptContribution,
  ExtensionSkillResourceContribution,
  ExtensionSkillToolContribution,
  ExternalDependencySource,
  ExtensionHostPortId,
  ManagedResourceContribution,
  ManagedResourcePackage,
  ManagedResourceProcess,
  ProductFeatureId,
  ProtocolBridgeContribution,
  ReadinessGateDeclaration,
  ReadinessProbe,
} from './schema-types';
export {
  validateExtensionManifest,
} from './validation';
export type { ExtensionContractValidation } from './validation';
