"""Cognition 使用的显式可观测性外部能力。"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class LoggerPort(Protocol):
    def debug(self, event: str, **values: Any) -> Any: ...
    def info(self, event: str, **values: Any) -> Any: ...
    def warning(self, event: str, **values: Any) -> Any: ...
    def error(self, event: str, **values: Any) -> Any: ...
    def critical(self, event: str, **values: Any) -> Any: ...


class SpanPort(Protocol):
    def set_attribute(self, name: str, value: Any) -> None: ...
    def add_event(self, name: str, attributes: dict | None = None) -> None: ...


class ObservabilityPort(Protocol):
    """由 Host composition 创建并注入；Port 本身不保存 process-global binding。"""

    def logger(self, module_name: str) -> LoggerPort: ...
    def counter(self, name: str, value: float = 1, labels: dict | None = None) -> None: ...
    def gauge(self, name: str, value: float, labels: dict | None = None) -> None: ...
    def histogram(self, name: str, value: float, labels: dict | None = None) -> None: ...
    def span(
        self, name: str, *, attributes: dict | None = None
    ) -> AbstractContextManager[SpanPort]: ...
    def trace_context(self, trace_id: str) -> AbstractContextManager[Any]: ...
    def new_trace_id(self) -> str: ...
    def current_trace_id(self) -> str | None: ...
