"""Cognition 对持久化能力的外部 Port。"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
import numpy as np

from glimmer_cradle.cognition.domain.conversation.models import ConversationMessage
from glimmer_cradle.cognition.domain.experience.episode import Episode
from glimmer_cradle.cognition.domain.experience.events import Moment
from glimmer_cradle.cognition.domain.relationship import RelationshipRecord


@dataclass(frozen=True, slots=True)
class ConsolidationJob:
    job_id: str
    episode_id: str
    episode_version: int
    scene_id: str
    actor_id: str | None
    attempt_count: int


class ExperienceLedgerPort(Protocol):
    @property
    def base_dir(self) -> object: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def flush(self) -> None: ...
    def append(self, moment: Moment) -> Moment: ...
    def query(self, *, after_position: int = 0, limit: int | None = None) -> list[Moment]: ...
    def recent(self, *, limit: int, kinds: set[str] | None = None,
               scene_id: str | None = None,
               exclude_trace_id: str | None = None) -> list[Moment]: ...
    def verify(self) -> dict[str, object]: ...


class ExperienceRecorderPort(Protocol):
    @property
    def ledger(self) -> ExperienceLedgerPort: ...
    async def flush(self) -> None: ...
    def moments_after(self, position: int) -> list[Moment]: ...


class EpisodeProjectionPort(Protocol):
    async def start(self) -> None: ...
    async def project_pending(self, *, seal: bool = False) -> int: ...
    def pending_consolidation(self, *, limit: int = 8) -> list[Episode]: ...
    def get_episode(self, episode_id: str) -> Episode | None: ...
    def recover_interrupted(self) -> None: ...
    def list_episodes(self, *, since_iso: str | None = None,
                      limit: int = 100) -> list[Episode]: ...
    def mark_consolidated(self, episode_id: str, consolidated_at: str) -> None: ...


class ConsolidationJobRepositoryPort(Protocol):
    async def recover_expired(self) -> None: ...
    async def enqueue(self, episode: Episode, *, debounce_seconds: int,
                      max_wait_seconds: int) -> None: ...
    async def claim_due(self, *, limit: int, lease_seconds: int) -> list[ConsolidationJob]: ...
    async def complete(self, jobs: list[ConsolidationJob]) -> None: ...
    async def fail(self, jobs: list[ConsolidationJob], *, error_code: str,
                   retry_base_seconds: int) -> None: ...


class MemoryRepositoryPort(Protocol):
    async def all_current(self) -> list[dict]: ...
    async def create_revisions(self, drafts: list[dict]) -> list[str]: ...


class KnowledgeRepositoryPort(Protocol):
    async def get_all_entries(self) -> list[dict]: ...
    async def replace_config_entries(self, entries: list[dict]) -> None: ...


class VectorRepositoryPort(Protocol):
    async def get_vectors(self, owner_kind: str, model: str) -> dict[str, np.ndarray]: ...
    async def upsert_vector(self, *, owner_kind: str, owner_id: str,
                            model: str, vector: np.ndarray) -> None: ...


class RelationshipRepositoryPort(Protocol):
    async def get(self, actor_id: str) -> RelationshipRecord | None: ...
    async def observe(self, actor_id: str, *, kind: str,
                      evidence_moment_id: str,
                      display_name: str | None = None) -> RelationshipRecord: ...


class RelationshipProjectionPort(Protocol):
    async def project_pending(self) -> int: ...


class ConversationStorePort(Protocol):
    @property
    def history_result_limit(self) -> int: ...
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def checkpoint(self) -> int: ...
    async def project(self, moment: Moment) -> bool: ...
    async def load_working_set(
        self, conversation_id: str, *, limit: int
    ) -> tuple[dict, list[ConversationMessage]]: ...
    async def retrieve_segments(self, conversation_id: str, query: str, *,
                                allowed_scopes: set[str], limit: int) -> list[str]: ...
    async def load_history_page(self, conversation_id: str, *,
                                allowed_scopes: set[str], cursor: str | None,
                                limit: int, scene_id: str | None = None,
                                actor_id: str | None = None) -> tuple[dict, list, str | None, bool]: ...
