/* Kernel domain error vocabulary；跨边界稳定 code 由 Adapter 映射。 */

/** 未迁移 runtime 结构使用的跨层错误码，字符串枚举且值=名。Kernel↔Cognition Service 错误已由 contracts Protobuf typed detail 拥有。归并历史：CORE_ERROR/UNKNOWN_ERROR→UNKNOWN；BRIDGE_ERROR/ADAPTER_ERROR→IPC_ERROR。 */
export type ErrorCode =
  | 'UNKNOWN'
  | 'CONFIG_ERROR'
  | 'LIFECYCLE_ERROR'
  | 'IPC_ERROR'
  | 'IPC_TIMEOUT'
  | 'PERSISTENCE_ERROR'
  | 'INFERENCE_ERROR'
  | 'CANCELLED'
  | 'EXTENSION_ERROR'
  | 'EXTENSION_VALIDATION_FAILED'
  | 'EXTENSION_SANDBOX_ERROR'
  | 'EXTENSION_PERMISSION_DENIED'
  | 'EXTENSION_LIFECYCLE_ERROR'
  | 'DOMAIN_ERROR'
  | 'MEMORY_NOT_FOUND'
  | 'PERSONA_VIOLATION'
  | 'EMOTION_ERROR';

/** ErrorCode 值访问对象（ErrorCode.XXX）。 */
export const ErrorCode = {
  UNKNOWN: 'UNKNOWN',
  CONFIG_ERROR: 'CONFIG_ERROR',
  LIFECYCLE_ERROR: 'LIFECYCLE_ERROR',
  IPC_ERROR: 'IPC_ERROR',
  IPC_TIMEOUT: 'IPC_TIMEOUT',
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
  INFERENCE_ERROR: 'INFERENCE_ERROR',
  CANCELLED: 'CANCELLED',
  EXTENSION_ERROR: 'EXTENSION_ERROR',
  EXTENSION_VALIDATION_FAILED: 'EXTENSION_VALIDATION_FAILED',
  EXTENSION_SANDBOX_ERROR: 'EXTENSION_SANDBOX_ERROR',
  EXTENSION_PERMISSION_DENIED: 'EXTENSION_PERMISSION_DENIED',
  EXTENSION_LIFECYCLE_ERROR: 'EXTENSION_LIFECYCLE_ERROR',
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  MEMORY_NOT_FOUND: 'MEMORY_NOT_FOUND',
  PERSONA_VIOLATION: 'PERSONA_VIOLATION',
  EMOTION_ERROR: 'EMOTION_ERROR',
} as const satisfies Record<string, ErrorCode>;
