import type { Meta, StoryObj } from '@storybook/react';
import { Configuration } from './Configuration';
import { ConfigurationController } from './ConfigurationController';
import { configurationScenario } from '../../../../tests/ui/scenarios/configuration';
import { snapshotToDraft } from './configuration-state';
const controller = new ConfigurationController();
const configuration = configurationScenario();
const snapshot = { ...controller.getSnapshot(), connected: true, configuration, draft: snapshotToDraft(configuration) };
const meta = { title: 'Features/Configuration', component: Configuration, args: { controller, snapshot, section: 'models', onSection: () => {} } } satisfies Meta<typeof Configuration>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Empty: Story = {};
export const Loading: Story = { args: { snapshot: { ...snapshot, configuration: null, draft: null, loading: true } } };
export const Error: Story = { args: { snapshot: { ...snapshot, configuration: null, draft: null, status: { kind: 'error', message: '无法读取配置，请重试。' } } } };
export const Pending: Story = { args: { snapshot: { ...snapshot, pending: true, status: { kind: 'saving', message: '正在保存配置…' } } } };
export const Conflict: Story = { args: { snapshot: { ...snapshot, draft: { ...snapshot.draft, revision: 'previous' }, status: { kind: 'error', message: '配置修订冲突，已保留本地草稿。请刷新或丢弃修改后重新编辑。' } } } };
export const Disconnected: Story = { args: { snapshot: { ...snapshot, connected: false } } };
export const Audio: Story = { args: { section: 'audio' } };
export const LongProvider: Story = { args: { snapshot: { ...snapshot, configuration: configurationScenario(false), draft: { ...snapshotToDraft(configurationScenario(false)), providers: [{ ...snapshotToDraft(configurationScenario(false)).providers[0], key: 'long-provider-name-'.repeat(12) }] } } } };
