import { useState, type ReactNode } from 'react';
import { Button, Dialog, DialogTrigger, Heading, Modal, ModalOverlay } from 'react-aria-components';
import { createProviderDraft, type ProviderDraftState } from './configuration-state';
import { isDraftDirty, routeModelOptions, validateDraft } from './configuration-draft-helpers';
import type { ConfigurationController, ConfigurationState } from './ConfigurationController';
import { ConfigurationFields, audioFields, embeddingFields, memoryFields, skillFields, mcpFields, setConfigurationPath } from './ConfigurationFields';
import styles from './Configuration.module.css';

export const configurationSections = [['models', '模型与路由'], ['audio', '音频'], ['embedding', '语义向量'], ['memory', '记忆与经验'], ['skills', 'Skill / MCP'], ['security', '安全与访问'], ['operations', '存储与服务']] as const;
export type ConfigurationSection = typeof configurationSections[number][0];
type Props = { snapshot: ConfigurationState; controller: ConfigurationController; section: ConfigurationSection; onSection: (section: ConfigurationSection) => void };
function ConfigurationNavigation({ section, onSection }: Pick<Props, 'section' | 'onSection'>) {
  const items = (close?: () => void) => configurationSections.map(([id, label]) => <button key={id} type="button" aria-current={section === id ? 'page' : undefined} onClick={() => { onSection(id); close?.(); }}>{label}</button>);
  return <><nav className={styles.navigation} aria-label="设置分类">{items()}</nav><div className={styles.mobileNavigation}><DialogTrigger><Button className="quiet-button">选择设置分类</Button><span>{configurationSections.find(([id]) => id === section)?.[1]}</span><ModalOverlay className={`${styles.overlay} ${styles.navigationOverlay}`} isDismissable><Modal className={`${styles.dialog} ${styles.navigationDialog}`}><Dialog>{({ close }) => <><Heading slot="title">设置分类</Heading><nav className={styles.drawerNavigation} aria-label="设置分类">{items(close)}</nav><Button className="quiet-button" onPress={close}>关闭分类</Button></>}</Dialog></Modal></ModalOverlay></DialogTrigger></div></>;
}
function Confirm({ label, disabled, onConfirm, children }: { label: string; disabled?: boolean; onConfirm: () => void; children: ReactNode }) {
  return <DialogTrigger><Button className="quiet-button" isDisabled={disabled}>{label}</Button><ModalOverlay className={styles.overlay} isDismissable><Modal className={styles.dialog}><Dialog>{({ close }) => <><Heading slot="title">{label}</Heading><p>{children}</p><div className={styles.actions}><Button className="quiet-button" onPress={close}>取消</Button><Button className="primary-button" onPress={() => { onConfirm(); close(); }}>确认{label}</Button></div></>}</Dialog></Modal></ModalOverlay></DialogTrigger>;
}
export function Configuration({ snapshot: state, controller, section, onSection }: Props) {
  const [selected, select] = useState(0);
  const [tokenLabel, setTokenLabel] = useState('');
  const draft = state.draft; const configuration = state.configuration;
  const locked = state.pending || state.loading;
  const dirty = isDraftDirty(configuration, draft);
  const validation = dirty ? validateDraft(draft) : null;
  const selectedIndex = draft && selected < draft.providers.length ? selected : 0;
  const provider = draft?.providers[selectedIndex];
  const editProvider = (edit: (provider: ProviderDraftState) => void) => controller.edit(next => { if (next.providers[selectedIndex]) edit(next.providers[selectedIndex]); });
  const field = (label: string, key: keyof Pick<ProviderDraftState, 'key' | 'api_type' | 'base_url' | 'api_key' | 'temperature'>, id: string, type = 'text') => <label className={styles.field}><span>{label}</span><input type={type} data-field={id} value={String(provider?.[key] ?? '')} autoComplete={type === 'password' ? 'new-password' : 'off'} placeholder={key === 'api_key' ? provider?.has_api_key ? '已写入，留空表示保持不变' : '未写入' : undefined} onChange={event => { const value = event.target.value; controller.edit(next => { const item = next.providers[selectedIndex]; if (key === 'key' && next.defaultRouteProviderKey === item.key) next.defaultRouteProviderKey = value; item[key] = value; }); }} /></label>;
  const systemFields = (fields: Parameters<typeof ConfigurationFields>[0]['fields']) => draft && <ConfigurationFields fields={fields} draft={draft} edit={(path, value) => controller.edit(next => setConfigurationPath(next, path, value))} />;
  return <section className={styles.page} data-role="view-settings">
    <header className={styles.header}><div><h1>服务配置</h1><p>按需调整模型、增强能力和服务管理。</p></div><Button className="quiet-button" isDisabled={!state.connected || locked} onPress={() => { void controller.reload(); void controller.refreshSupplemental(); }}>刷新</Button></header>
    {!state.connected && <p role="status">控制面连接已断开，草稿保留；重连后可继续编辑。</p>}
    <ConfigurationNavigation section={section} onSection={next => { if (section === 'security') controller.hideToken(); onSection(next); }} />
    {state.loading && <p role="status">正在读取配置快照…</p>}
    {draft && configuration ? <>
      <fieldset className={styles.content} disabled={locked} aria-busy={locked}>
        {section === 'models' && <>
          <section className={styles.summary} data-role="route-summary"><h2>{configuration.llm.default_route.ready ? '默认对话路由可用' : '默认对话路由未就绪'}</h2><p>{configuration.llm.default_route.ready ? `${configuration.llm.default_route.provider_key} / ${configuration.llm.default_route.model_alias}` : configuration.llm.default_route.reason}</p></section>
          <section><div className={styles.sectionHead}><h2>LLM Provider</h2><button className="quiet-button" data-action="add-provider" onClick={() => { const keys = new Set(draft.providers.map(item => item.key)); let index = 1; while (keys.has(`provider-${index}`)) index++; controller.edit(next => { next.providers.push(createProviderDraft(`provider-${index}`)); }); select(draft.providers.length); }}>新增 Provider</button></div>
            <div className={styles.providers}><div className={styles.providerList} data-role="provider-list">{draft.providers.length ? draft.providers.map((item, index) => <button key={index} className={styles.provider} aria-pressed={index === selectedIndex} onClick={() => select(index)}><strong>{item.key || '未命名 Provider'}</strong><span>{item.api_type} · {item.has_api_key ? '已写入密钥' : '未写入密钥'}</span></button>) : <p>还没有 Provider。新增模型后即可配置对话路由。</p>}</div>
              <div data-role="provider-editor">{provider ? <><div className={styles.sectionHead}><h3>{provider.key || '未命名 Provider'}</h3><button className="quiet-button" data-action="remove-provider" onClick={() => { controller.edit(next => { const key = next.providers[selectedIndex].key; next.providers.splice(selectedIndex, 1); if (next.defaultRouteProviderKey === key) { next.defaultRouteProviderKey = ''; next.defaultRouteModelAlias = ''; } }); select(0); }}>删除 Provider</button></div><div className={styles.fields}>{field('Provider key', 'key', 'provider-key')}{field('API 协议', 'api_type', 'provider-api-type')}{field('Base URL', 'base_url', 'provider-base-url', 'url')}{field('API Key', 'api_key', 'provider-api-key', 'password')}{field('温度', 'temperature', 'provider-temperature', 'number')}<label className={styles.field}><span>清除已保存 API Key</span><input type="checkbox" data-field="provider-clear-secret" checked={provider.clear_api_key} onChange={event => editProvider(item => { item.clear_api_key = event.target.checked; })} /></label></div>
              <Button className="quiet-button" data-action="test-provider" isDisabled={!state.connected || locked} onPress={() => void controller.testProvider(selectedIndex)}>测试连接并发现模型</Button>
              <div className={styles.sectionHead}><h3>模型别名</h3><button className="quiet-button" data-action="add-model" onClick={() => editProvider(item => { item.models.push({ alias: '', model_id: '' }); })}>新增模型</button></div>{provider.models.map((model, index) => <div className={styles.model} key={index}><label className={styles.field}><span>别名 {index + 1}</span><input data-model-alias={index} value={model.alias} onChange={event => editProvider(item => { item.models[index].alias = event.target.value; })} /></label><label className={styles.field}><span>模型 ID {index + 1}</span><input data-model-id={index} value={model.model_id} onChange={event => editProvider(item => { item.models[index].model_id = event.target.value; })} /></label><button className="quiet-button" aria-label={`删除模型 ${index + 1}`} onClick={() => editProvider(item => { item.models.splice(index, 1); })}>删除</button></div>)}</> : <p>选择或新增一个 Provider。</p>}</div>
            </div>
          </section>
          <section><h2>对话模型选择</h2><div className={styles.fields}><label className={styles.field}><span>默认 Provider</span><select data-field="default-route-provider" value={draft.defaultRouteProviderKey} onChange={event => controller.edit(next => { next.defaultRouteProviderKey = event.target.value; next.defaultRouteModelAlias = routeModelOptions(next)[0]?.alias ?? ''; })}><option value="">未选择</option>{draft.providers.map((item, index) => <option key={index} value={item.key}>{item.key}</option>)}</select></label><label className={styles.field}><span>默认模型</span><select data-field="default-route-model" value={draft.defaultRouteModelAlias} disabled={!draft.defaultRouteProviderKey} onChange={event => controller.edit(next => { next.defaultRouteModelAlias = event.target.value; })}><option value="">未选择</option>{routeModelOptions(draft).map((model, index) => <option key={index} value={model.alias}>{model.alias} · {model.model_id}</option>)}</select></label></div></section>
        </>}
        {section === 'audio' && <section data-role="audio-section"><h2>音频增强</h2><p>默认关闭；启用后校验路由与资源。</p>{systemFields(audioFields)}</section>}
        {section === 'embedding' && <section data-role="embedding-section"><h2>语义向量增强</h2><p>关闭时不影响基础对话；启用后提供语义检索。</p>{systemFields(embeddingFields)}</section>}
        {section === 'memory' && <section data-role="memory-section"><h2>上下文与经验</h2><p>聊天时间线与长期经验分开管理。</p>{systemFields(memoryFields)}</section>}
        {section === 'skills' && <section data-role="skills-section"><div className={styles.sectionHead}><h2>Skill Plane / MCP</h2><button className="quiet-button" data-action="add-mcp-server" onClick={() => controller.edit(next => { const servers = next.skills.mcp_servers ??= []; let index = 1; while (servers.some(server => server.id === `server-${index}`)) index++; servers.push({ id: `server-${index}`, transport: 'stdio', enabled: true, products: ['personal-server'], command: '', args: [], env: {}, timeout_ms: 30000 }); })}>新增 MCP Server</button></div>{systemFields(skillFields)}{draft.skills.mcp_servers?.length ? draft.skills.mcp_servers.map((server, index) => <article className={styles.item} key={index}><div className={styles.sectionHead}><h3>{server.id || '未命名 MCP Server'}</h3><button className="quiet-button" aria-label={`删除 MCP Server ${index + 1}`} onClick={() => controller.edit(next => { next.skills.mcp_servers!.splice(index, 1); })}>删除</button></div>{systemFields(mcpFields(index))}</article>) : <p>尚未配置 MCP Server。</p>}
          <h3>Skill Catalog / Provider Runtime</h3>{state.skillsPending && <p role="status">正在读取技能目录…</p>}{state.skills?.snapshot && state.skills.status === 'success' ? <><p>{state.skills.snapshot.totalSkills} 个技能 · ready {state.skills.snapshot.runtimeStatusCounts.ready} / contract_only {state.skills.snapshot.runtimeStatusCounts.contract_only}</p>{state.skills.snapshot.providerRuntimes.map(runtime => <article className={styles.item} key={runtime.provider.id}><h4>{runtime.display_name || runtime.provider.id}</h4><p>{runtime.state} · {runtime.summary}</p><p>Skills {runtime.skill_count} · Tools {runtime.tool_count} · Resources {runtime.resource_count}</p><p>{runtime.error} {runtime.recovery_actions?.join(' / ')}</p></article>)}{state.skills.snapshot.entries.map((entry, index) => <article className={styles.item} key={index}><h4>{entry.name}</h4><p>{entry.description}</p><p>{String(entry.metadata?.runtime_status ?? 'unknown')} · {entry.audience} · {entry.scope.kind}</p><p>{entry.provider.kind} · {entry.scope.kind}{'ids' in entry.scope ? `:${entry.scope.ids?.join(', ')}` : ''}</p><p>Tools {entry.tools.length} · Resources {entry.resources.length} · Prompts {entry.prompts.length}</p><p>Risk: {entry.policy.riskLevel} · Confirm: {entry.policy.confirmationRequired ? 'yes' : 'no'} · Audit: {entry.policy.audit ? 'yes' : 'no'}</p><p>可见性：{String(entry.metadata?.visibility ?? '未声明')}</p><p>{String(entry.metadata?.readiness_reason ?? '')}</p></article>)}</> : <p>{state.skills?.message || '尚未获取技能目录。'}</p>}</section>}
        {section === 'security' && <section data-role="security-access-section"><h2>控制面登录边界</h2><p>{state.tokens?.mode} · {state.tokens?.message}</p>{state.tokenError && <p role="alert">{state.tokenError}</p>}<div className={styles.actions}><label className={styles.field}><span>新令牌标签</span><input data-field="access-token-label" value={tokenLabel} disabled={state.tokenPending} onChange={event => setTokenLabel(event.target.value)} /></label><Button className="primary-button" data-action="create-token" isDisabled={!state.connected || state.tokenPending || !tokenLabel.trim()} onPress={() => void controller.mutateToken('create', tokenLabel)}>创建访问令牌</Button><Button className="quiet-button" isDisabled={!state.connected || state.tokenPending} onPress={() => void controller.refreshSupplemental()}>重读访问状态</Button></div>{state.tokenResult && <div role="status"><p>{state.tokenResult.message}</p>{state.tokenResult.issued_token && <><strong>新令牌明文仅显示一次</strong><code className={styles.secret} data-role="issued-access-token">{state.tokenResult.issued_token}</code><Button className="quiet-button" onPress={() => controller.hideToken()}>隐藏令牌</Button></>}</div>}{state.tokens?.tokens.map(token => <article className={styles.item} key={token.token_id}><h3>{token.label}</h3><p>{token.source} · {token.scopes.join(', ')}</p><p>{token.disabled_reason}</p><div className={styles.actions}><Button className="quiet-button" isDisabled={!state.connected || state.tokenPending || !token.rotatable} onPress={() => void controller.mutateToken('rotate', token.token_id)}>轮换</Button><Confirm label="撤销令牌" disabled={!state.connected || state.tokenPending || !token.revocable} onConfirm={() => void controller.mutateToken('revoke', token.token_id)}>撤销「{token.label}」后，该令牌将无法继续访问控制面。</Confirm></div></article>)}</section>}
        {section === 'operations' && <><section data-role="storage-backup-section"><h2>存储与备份</h2><div className={styles.item}><p>配置：{configuration.storage.config_root}</p><p>数据：{configuration.storage.data_root}</p><p>状态：{configuration.storage.state_root}</p></div><p>{state.operationsError || state.operations?.backup.disabled_reason}</p><Button className="primary-button" data-action="create-backup" isDisabled={!state.connected || state.operationPending || !state.operations?.backup.supported} onPress={() => void controller.runOperation('backup.create')}>创建备份</Button>{state.operations?.backup.entries.map(entry => <article className={styles.item} key={entry.backup_id}><h3>{entry.backup_id}</h3><p>{entry.status}</p><Confirm label="恢复备份" disabled={!state.connected || state.operationPending || !state.operations?.backup.supported} onConfirm={() => void controller.runOperation('backup.restore', entry.backup_id)}>恢复「{entry.backup_id}」会替换当前受管数据。</Confirm></article>)}</section><section data-role="updates-service-section"><h2>更新与服务控制</h2><p>{configuration.service.cognition_ready ? 'Cognition 已就绪' : 'Cognition 未就绪'}</p><p>{state.operations?.update.disabled_reason || state.operations?.service.disabled_reason}</p><p>当前版本 {state.operations?.update.current_version || 'unknown'}{state.operations?.update.available_version && ` · 候选 ${state.operations.update.available_version}`}</p><div className={styles.actions}><Button className="quiet-button" data-action="check-updates" isDisabled={!state.connected || state.operationPending || !state.operations?.update.check_supported} onPress={() => void controller.runOperation('update.check')}>检查更新</Button><Confirm label="应用更新" disabled={!state.connected || state.operationPending || !state.operations?.update.apply_supported} onConfirm={() => void controller.runOperation('update.apply')}>应用受管更新，服务可能短暂中断。</Confirm><Confirm label="重启服务" disabled={!state.connected || state.operationPending || !state.operations?.service.restart_supported} onConfirm={() => void controller.runOperation('service.restart')}>重启服务后会重新连接控制面。</Confirm><Confirm label="停止服务" disabled={!state.connected || state.operationPending || !state.operations?.service.stop_supported} onConfirm={() => void controller.runOperation('service.stop')}>停止服务后需在部署环境重新启动。</Confirm></div></section>{state.operationResult && <p role="status">{state.operationResult.message} · {state.operationResult.operation_id} · {state.operationResult.status}</p>}{state.operationPending && <p role="status">正在等待事务结果…</p>}</>}
      </fieldset>
      <footer className={styles.saveBar} data-role="save-bar"><div><span>修订 {draft.revision}</span><p>{dirty ? '有未保存修改' : '已与配置快照同步'}</p></div><div role="status" data-role="save-status"><p>{state.status.message}</p>{state.status.summary?.length ? <ul>{state.status.summary.map((line, index) => <li key={index}>{line}</li>)}</ul> : null}{validation && <p>{validation}</p>}</div><div className={styles.actions}><Confirm label="丢弃修改" disabled={!dirty || locked} onConfirm={() => controller.discard()}>所有设置子区的未保存修改将被丢弃。</Confirm><Button className="quiet-button" data-action="preview" isDisabled={!state.connected || locked || !dirty || !!validation} onPress={() => void controller.submit(true)}>预览变更</Button><Button className="primary-button" data-action="save" isDisabled={!state.connected || locked || !dirty || !!validation} onPress={() => void controller.submit(false)}>保存并应用</Button></div></footer>
    </> : !state.loading && <div role="alert"><p>{state.status.message || '等待控制面提供配置。'}</p><Button className="quiet-button" isDisabled={!state.connected} onPress={() => void controller.reload()}>重试读取</Button></div>}
  </section>;
}
