import { useEffect, useState, type ReactNode } from 'react';
import { Button, Dialog, DialogTrigger, Heading, Modal, ModalOverlay } from 'react-aria-components';
import { createProviderDraft, type ProviderDraftState } from './configuration-state';
import { isDraftDirty, routeModelOptions, validateDraft } from './configuration-draft-helpers';
import type { ConfigurationController, ConfigurationState } from './ConfigurationController';
import { ConfigurationFields, audioFields, embeddingFields, memoryFields, skillFields, mcpFields, setConfigurationPath } from './ConfigurationFields';
import styles from './Configuration.module.css';
import { SystemNavigation } from '../../shared/ui/SystemNavigation/SystemNavigation';
import { SelectField } from '../../shared/ui/SelectField/SelectField';
import type { SkillCatalogSnapshot } from '../../../shared/control-center-models';
import { ConfirmationDialog } from '../../shared/ui/ConfirmationDialog/ConfirmationDialog';

export const configurationSections = [['models', 'AI 与路由'], ['audio', '语音与音频'], ['embedding', '检索增强'], ['memory', '记忆与检索'], ['skills', '能力接入'], ['security', '安全'], ['operations', '存储与运行']] as const;
export const configurationNavigationSections = configurationSections.slice(0, 4);
export type ConfigurationSection = typeof configurationSections[number][0];
type Props = { snapshot: ConfigurationState; controller: ConfigurationController; section: ConfigurationSection; standalone?: boolean; system?: boolean; onSection: (section: ConfigurationSection) => void };
function ConfigurationNavigation({ section, onSection }: Pick<Props, 'section' | 'onSection'>) {
  const items = (close?: () => void) => configurationNavigationSections.map(([id, label]) => <button key={id} type="button" aria-current={section === id ? 'page' : undefined} onClick={() => { onSection(id); close?.(); }}>{label}</button>);
  return <><nav className={styles.navigation} aria-label="配置分类">{items()}</nav><div className={styles.mobileNavigation}><DialogTrigger><Button className="quiet-button">选择配置分类</Button><span>{configurationSections.find(([id]) => id === section)?.[1]}</span><ModalOverlay className={`${styles.overlay} ${styles.navigationOverlay}`} isDismissable><Modal className={`${styles.dialog} ${styles.navigationDialog}`}><Dialog>{({ close }) => <><Heading slot="title">配置分类</Heading><nav className={styles.drawerNavigation} aria-label="配置分类">{items(close)}</nav><Button className="quiet-button" onPress={close}>关闭分类</Button></>}</Dialog></Modal></ModalOverlay></DialogTrigger></div></>;
}
const Confirm = ConfirmationDialog;
export function Configuration({ snapshot: state, controller, section, standalone = false, system = false, onSection }: Props) {
  useEffect(() => {
    // 子区由 URL/history 驱动，离开安全页也必须撤销迟到响应的明文展示资格。
    if (section === 'security') return () => controller.hideToken();
  }, [controller, section]);
  const [selected, select] = useState(0);
  const [tokenLabel, setTokenLabel] = useState('');
  const draft = state.draft; const configuration = state.configuration;
  const locked = state.pending || state.loading;
  const dirty = isDraftDirty(configuration, draft);
  const validation = dirty ? validateDraft(draft) : null;
  const selectedIndex = draft && selected < draft.providers.length ? selected : 0;
  const provider = draft?.providers[selectedIndex];
  const editProvider = (edit: (provider: ProviderDraftState) => void) => controller.edit(next => { if (next.providers[selectedIndex]) edit(next.providers[selectedIndex]); });
  const field = (label: string, key: keyof Pick<ProviderDraftState, 'key' | 'api_type' | 'base_url' | 'api_key' | 'temperature'>, id: string, type = 'text') => <label className={styles.field}><span>{label}</span><input type={type} data-field={id} value={String(provider?.[key] ?? '')} autoComplete={type === 'password' ? 'new-password' : 'off'} placeholder={key === 'api_key' ? provider?.has_api_key ? '已写入，留空表示保持不变' : '未写入' : undefined} onChange={event => { const value = event.target.value; controller.edit(next => { const item = next.providers[selectedIndex]; if (key === 'key' && next.defaultRouteProviderKey === item.key) next.defaultRouteProviderKey = value; item[key] = value; }); }} /></label>;
  const systemFields = (fields: Parameters<typeof ConfigurationFields>[0]['fields']) => draft && <ConfigurationFields fields={fields} draft={draft} edit={(path, value) => controller.edit(next => setConfigurationPath(next, path, value))} />;
  return <section className={`${styles.page} ${standalone ? styles.standalone : ''} ${standalone && !system ? styles.capability : ''}`} data-role={system ? 'view-system-settings' : standalone ? 'view-capability-catalog' : 'view-config'}>
    {system && <SystemNavigation />}
    <div className={styles.pageTools}><Button className="quiet-button" isDisabled={!state.connected || locked} onPress={() => { void controller.reload(); void controller.refreshSupplemental(); }}>刷新</Button></div>
    {!state.connected && <p role="status">控制面连接已断开，草稿保留；重连后可继续编辑。</p>}
    {!standalone && <ConfigurationNavigation section={section} onSection={onSection} />}
    {state.loading && <p role="status">正在读取配置快照…</p>}
    {draft && configuration ? <>
      <fieldset className={styles.content} disabled={locked} aria-busy={locked}>
        {section === 'models' && <>
          <section><div className={styles.providerActions}><button className="quiet-button" data-action="add-provider" onClick={() => { const keys = new Set(draft.providers.map(item => item.key)); let index = 1; while (keys.has(`provider-${index}`)) index++; controller.edit(next => { next.providers.push(createProviderDraft(`provider-${index}`)); }); select(draft.providers.length); }}>新增 Provider</button></div>
            <div className={styles.providers}><nav className={styles.providerList} data-role="provider-list" aria-label="Provider 目录">{draft.providers.length ? draft.providers.map((item, index) => <button key={index} className={styles.provider} aria-pressed={index === selectedIndex} onClick={() => select(index)}>{item.key || '未命名 Provider'}</button>) : <p>还没有 Provider。</p>}</nav>
              <div data-role="provider-editor">{provider ? <><div className={styles.sectionHead}><h3>{provider.key || '未命名 Provider'}</h3><button className="quiet-button" data-action="remove-provider" onClick={() => { controller.edit(next => { const key = next.providers[selectedIndex].key; next.providers.splice(selectedIndex, 1); if (next.defaultRouteProviderKey === key) { next.defaultRouteProviderKey = ''; next.defaultRouteModelAlias = ''; } }); select(0); }}>删除 Provider</button></div><div className={styles.fields}>{field('Provider key', 'key', 'provider-key')}{field('API 协议', 'api_type', 'provider-api-type')}{field('Base URL', 'base_url', 'provider-base-url', 'url')}{field('API Key', 'api_key', 'provider-api-key', 'password')}{field('温度', 'temperature', 'provider-temperature', 'number')}<label className={styles.field}><span>清除已保存 API Key</span><input type="checkbox" data-field="provider-clear-secret" checked={provider.clear_api_key} onChange={event => editProvider(item => { item.clear_api_key = event.target.checked; })} /></label></div>
              <Button className="quiet-button" data-action="test-provider" isDisabled={!state.connected || locked} onPress={() => void controller.testProvider(selectedIndex)}>测试连接并发现模型</Button>
              <div className={styles.sectionHead}><h3>模型别名</h3><button className="quiet-button" data-action="add-model" onClick={() => editProvider(item => { item.models.push({ alias: '', model_id: '' }); })}>新增模型</button></div>{provider.models.map((model, index) => <div className={styles.model} key={index}><label className={styles.field}><span>别名 {index + 1}</span><input data-model-alias={index} value={model.alias} onChange={event => editProvider(item => { item.models[index].alias = event.target.value; })} /></label><label className={styles.field}><span>模型 ID {index + 1}</span><input data-model-id={index} value={model.model_id} onChange={event => editProvider(item => { item.models[index].model_id = event.target.value; })} /></label><button className="quiet-button" aria-label={`删除模型 ${index + 1}`} onClick={() => editProvider(item => { item.models.splice(index, 1); })}>删除</button></div>)}</> : <p>选择或新增一个 Provider。</p>}</div>
            </div>
          </section>
          <section><h2>对话模型选择</h2><div className={styles.fields}><SelectField label="默认 Provider" dataField="default-route-provider" value={draft.defaultRouteProviderKey} options={[{ value: '', label: '未选择' }, ...draft.providers.map((item) => ({ value: item.key, label: item.key }))]} onChange={(value) => controller.edit(next => { next.defaultRouteProviderKey = value; next.defaultRouteModelAlias = routeModelOptions(next)[0]?.alias ?? ''; })} /><SelectField label="默认模型" dataField="default-route-model" value={draft.defaultRouteModelAlias} disabled={!draft.defaultRouteProviderKey} options={[{ value: '', label: '未选择' }, ...routeModelOptions(draft).map((model) => ({ value: model.alias, label: `${model.alias} · ${model.model_id}` }))]} onChange={(value) => controller.edit(next => { next.defaultRouteModelAlias = value; })} /></div></section>
        </>}
        {section === 'audio' && <section data-role="audio-section"><h2>音频增强</h2><p>默认关闭；启用后校验路由与资源。</p>{systemFields(audioFields)}</section>}
        {section === 'embedding' && <section data-role="embedding-section"><h2>语义向量增强</h2><p>关闭时不影响基础对话；启用后提供语义检索。</p>{systemFields(embeddingFields)}</section>}
        {section === 'memory' && <section data-role="memory-section"><h2>上下文与经验</h2><p>聊天时间线与长期经验分开管理。</p>{systemFields(memoryFields)}</section>}
        {section === 'skills' && <section data-role="skills-section">
          {state.skillsPending && <p role="status">正在读取技能目录…</p>}
          {state.skills?.snapshot && state.skills.status === 'success' ? <CapabilityBrowser snapshot={state.skills.snapshot} management={<><div className={styles.sectionHead}><div><h4>接入管理</h4><p>管理本地技能目录与 MCP Server。</p></div><button className="quiet-button" data-action="add-mcp-server" onClick={() => controller.edit(next => { const servers = next.skills.mcp_servers ??= []; let index = 1; while (servers.some(server => server.id === `server-${index}`)) index++; servers.push({ id: `server-${index}`, transport: 'stdio', enabled: true, products: ['personal-server'], command: '', args: [], env: {}, timeout_ms: 30000 }); })}>添加 MCP</button></div>{systemFields(skillFields)}{draft.skills.mcp_servers?.length ? draft.skills.mcp_servers.map((server, index) => <article className={styles.item} key={index}><div className={styles.sectionHead}><h3>{server.id || '未命名 MCP Server'}</h3><button className="quiet-button" aria-label={`删除 MCP Server ${index + 1}`} onClick={() => controller.edit(next => { next.skills.mcp_servers!.splice(index, 1); })}>删除</button></div>{systemFields(mcpFields(index))}</article>) : <p>暂无 MCP Server。</p>}</>} /> : <p>{state.skills?.message || '尚未获取技能目录。'}</p>}
        </section>}
        {section === 'security' && <section data-role="security-access-section"><h2>控制面登录边界</h2><p>{state.tokens?.mode} · {state.tokens?.message}</p>{state.tokenError && <p role="alert">{state.tokenError}</p>}<div className={styles.actions}><label className={styles.field}><span>新令牌标签</span><input data-field="access-token-label" value={tokenLabel} disabled={state.tokenPending} onChange={event => setTokenLabel(event.target.value)} /></label><Button className="primary-button" data-action="create-token" isDisabled={!state.connected || state.tokenPending || !tokenLabel.trim()} onPress={() => void controller.mutateToken('create', tokenLabel)}>创建访问令牌</Button><Button className="quiet-button" isDisabled={!state.connected || state.tokenPending} onPress={() => void controller.refreshSupplemental()}>重读访问状态</Button></div>{state.tokenResult && <div role="status"><p>{state.tokenResult.message}</p>{state.tokenResult.issued_token && <><strong>新令牌明文仅显示一次</strong><code className={styles.secret} data-role="issued-access-token">{state.tokenResult.issued_token}</code><Button className="quiet-button" onPress={() => controller.hideToken()}>隐藏令牌</Button></>}</div>}{state.tokens?.tokens.map(token => <article className={styles.item} key={token.token_id}><h3>{token.label}</h3><p>{token.source} · {token.scopes.join(', ')}</p><p>{token.disabled_reason}</p><div className={styles.actions}><Button className="quiet-button" isDisabled={!state.connected || state.tokenPending || !token.rotatable} onPress={() => void controller.mutateToken('rotate', token.token_id)}>轮换</Button><Confirm label="撤销令牌" disabled={!state.connected || state.tokenPending || !token.revocable} onConfirm={() => void controller.mutateToken('revoke', token.token_id)}>撤销「{token.label}」后，该令牌将无法继续访问控制面。</Confirm></div></article>)}</section>}
        {section === 'operations' && <><section data-role="storage-backup-section"><h2>存储与备份</h2><div className={styles.item}><p>配置：{configuration.storage.config_root}</p><p>数据：{configuration.storage.data_root}</p><p>状态：{configuration.storage.state_root}</p></div><p>{state.operationsError || state.operations?.backup.disabled_reason}</p><Button className="primary-button" data-action="create-backup" isDisabled={!state.connected || state.operationPending || !state.operations?.backup.supported} onPress={() => void controller.runOperation('backup.create')}>创建备份</Button>{state.operations?.backup.entries.map(entry => <article className={styles.item} key={entry.backup_id}><h3>{entry.backup_id}</h3><p>{entry.status}</p><Confirm label="恢复备份" disabled={!state.connected || state.operationPending || !state.operations?.backup.supported} onConfirm={() => void controller.runOperation('backup.restore', entry.backup_id)}>恢复「{entry.backup_id}」会替换当前受管数据。</Confirm></article>)}</section><section data-role="updates-service-section"><h2>更新与服务控制</h2><p>{configuration.service.cognition_ready ? 'Cognition 已就绪' : 'Cognition 未就绪'}</p><p>{state.operations?.update.disabled_reason || state.operations?.service.disabled_reason}</p><p>当前版本 {state.operations?.update.current_version || 'unknown'}{state.operations?.update.available_version && ` · 候选 ${state.operations.update.available_version}`}</p><div className={styles.actions}><Button className="quiet-button" data-action="check-updates" isDisabled={!state.connected || state.operationPending || !state.operations?.update.check_supported} onPress={() => void controller.runOperation('update.check')}>检查更新</Button><Confirm label="应用更新" disabled={!state.connected || state.operationPending || !state.operations?.update.apply_supported} onConfirm={() => void controller.runOperation('update.apply')}>应用受管更新，服务可能短暂中断。</Confirm><Confirm label="重启服务" disabled={!state.connected || state.operationPending || !state.operations?.service.restart_supported} onConfirm={() => void controller.runOperation('service.restart')}>重启服务后会重新连接控制面。</Confirm><Confirm label="停止服务" disabled={!state.connected || state.operationPending || !state.operations?.service.stop_supported} onConfirm={() => void controller.runOperation('service.stop')}>停止服务后需在部署环境重新启动。</Confirm></div></section>{state.operationResult && <p role="status">{state.operationResult.message} · {state.operationResult.operation_id} · {state.operationResult.status}</p>}{state.operationPending && <p role="status">正在等待事务结果…</p>}</>}
      </fieldset>
      <footer className={styles.saveBar} data-role="save-bar"><div><span>修订 {draft.revision}</span><p>{dirty ? '有未保存修改' : '已与配置快照同步'}</p></div><div role="status" data-role="save-status"><p>{state.status.message}</p>{state.status.summary?.length ? <ul>{state.status.summary.map((line, index) => <li key={index}>{line}</li>)}</ul> : null}{validation && <p>{validation}</p>}</div><div className={styles.actions}><Confirm label="丢弃修改" disabled={!dirty || locked} onConfirm={() => controller.discard()}>所有设置子区的未保存修改将被丢弃。</Confirm><Button className="quiet-button" data-action="preview" isDisabled={!state.connected || locked || !dirty || !!validation} onPress={() => void controller.submit(true)}>预览变更</Button><Button className="primary-button" data-action="save" isDisabled={!state.connected || locked || !dirty || !!validation} onPress={() => void controller.submit(false)}>保存并应用</Button></div></footer>
    </> : !state.loading && <div role="alert"><p>{state.status.message || '等待控制面提供配置。'}</p><Button className="quiet-button" isDisabled={!state.connected} onPress={() => void controller.reload()}>重试读取</Button></div>}
  </section>;
}

function CapabilityBrowser({ snapshot, management }: { readonly snapshot: SkillCatalogSnapshot; readonly management: ReactNode }): JSX.Element {
  const items = [
    ...snapshot.providerRuntimes.map((runtime) => ({
      id: `runtime:${runtime.provider.id}`,
      group: '运行体',
      label: runtime.display_name || runtime.provider.id,
      content: <><h4>{runtime.display_name || runtime.provider.id}</h4><p>{runtime.summary}</p><dl className={styles.capabilityFacts}><dt>状态</dt><dd>{runtime.state}</dd><dt>Provider</dt><dd>{runtime.provider.kind} · {runtime.provider.id}</dd><dt>内容</dt><dd>Skills {runtime.skill_count} · Tools {runtime.tool_count} · Resources {runtime.resource_count} · Prompts {runtime.prompt_count}</dd>{runtime.error && <><dt>错误</dt><dd>{runtime.error}</dd></>}{runtime.recovery_actions?.length ? <><dt>恢复建议</dt><dd>{runtime.recovery_actions.join(' / ')}</dd></> : null}</dl></>,
    })),
    ...snapshot.entries.map((entry, index) => ({
      id: `skill:${entry.id || `${entry.provider.id}:${entry.name}:${index}`}`,
      group: '技能',
      label: entry.name,
      content: <><h4>{entry.name}</h4><p>{entry.description}</p><dl className={styles.capabilityFacts}><dt>状态</dt><dd>{String(entry.metadata?.runtime_status ?? 'unknown')}</dd><dt>Provider</dt><dd>{entry.provider.kind} · {entry.provider.id}</dd><dt>范围</dt><dd>{entry.scope.kind}{entry.scope.ids?.length ? ` · ${entry.scope.ids.join(', ')}` : ''}</dd><dt>内容</dt><dd>Tools {entry.tools.length} · Resources {entry.resources.length} · Prompts {entry.prompts.length}</dd><dt>策略</dt><dd>Risk {entry.policy.riskLevel} · Confirm {entry.policy.confirmationRequired ? 'yes' : 'no'} · Audit {entry.policy.audit ? 'yes' : 'no'}</dd><dt>可见性</dt><dd>{String(entry.metadata?.visibility ?? '未声明')}</dd>{entry.metadata?.readiness_reason ? <><dt>就绪说明</dt><dd>{String(entry.metadata.readiness_reason)}</dd></> : null}</dl></>,
    })),
    { id: 'management', group: '接入', label: 'MCP 与本地技能', content: management },
  ];
  const [selectedId, setSelectedId] = useState(items[0]?.id || '');
  const selected = items.find((item) => item.id === selectedId) || items[0];
  return <div className={styles.capabilityBrowser}>
      <nav className={styles.capabilityRail} aria-label="能力目录">
        {items.map((item, index) => <div key={item.id}>{index === 0 || items[index - 1].group !== item.group ? <small className={styles.capabilityGroup}>{item.group}</small> : null}<Button className={styles.capabilityNavItem} aria-pressed={item.id === selected?.id} onPress={() => setSelectedId(item.id)}>{item.label}</Button></div>)}
      </nav>
      <article className={styles.capabilityDetail} data-role="capability-detail" aria-label={selected ? `${selected.label} 详情` : '能力详情'}>{selected?.content || <p>能力目录为空。</p>}</article>
    </div>;
}
