name: 构建 Desktop 固定制品

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm check:pr
      - run: pnpm --filter @glimmer-cradle/desktop package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: desktop-windows-x64-fixed-artifact
          path: dist/desktop/*/windows-x64/
          if-no-files-found: error
